-- Expand Lost reason taxonomy for EPC win/loss analysis (additive only).
ALTER TYPE "LostReason" ADD VALUE IF NOT EXISTS 'FINANCING_FAILED';
ALTER TYPE "LostReason" ADD VALUE IF NOT EXISTS 'NO_FEASIBILITY';
ALTER TYPE "LostReason" ADD VALUE IF NOT EXISTS 'SOCIETY_OR_LANDLORD_BLOCK';
ALTER TYPE "LostReason" ADD VALUE IF NOT EXISTS 'REGULATORY_DISCOM';
ALTER TYPE "LostReason" ADD VALUE IF NOT EXISTS 'CUSTOMER_NO_RESPONSE';
ALTER TYPE "LostReason" ADD VALUE IF NOT EXISTS 'WRONG_LEAD';
ALTER TYPE "LostReason" ADD VALUE IF NOT EXISTS 'DIY_OR_LOCAL_INSTALLER';
ALTER TYPE "LostReason" ADD VALUE IF NOT EXISTS 'PROPERTY_SOLD_OR_MOVED';
ALTER TYPE "LostReason" ADD VALUE IF NOT EXISTS 'CUSTOMER_INTERNAL_DISAGREEMENT';

ALTER TYPE "LostToCompetitionReason" ADD VALUE IF NOT EXISTS 'LOST_DUE_TO_TIMELINE';
ALTER TYPE "LostToCompetitionReason" ADD VALUE IF NOT EXISTS 'LOST_DUE_TO_BRAND_OR_WARRANTY';
