// ─────────────────────────────────────────────
// Shared costing constants — kept in a separate
// file so CostingSheet.tsx can be a pure React
// component file and Vite Fast Refresh works.
// ─────────────────────────────────────────────

export type Category =
  | 'pv-modules'
  | 'inverters'
  | 'mounting-structure'
  | 'dc-db'
  | 'ac-db'
  | 'dc-cable'
  | 'ac-cable'
  | 'earthing'
  | 'meter'
  | 'installation'
  | 'others';

export const CATEGORIES: { value: Category; label: string }[] = [
  { value: 'pv-modules',         label: 'PV Modules'        },
  { value: 'inverters',          label: 'Inverters'         },
  { value: 'mounting-structure', label: 'Mounting Structure' },
  { value: 'dc-db',              label: 'DC Dist. Board'    },
  { value: 'ac-db',              label: 'AC Dist. Board'    },
  { value: 'dc-cable',           label: 'DC Cable'          },
  { value: 'ac-cable',           label: 'AC Cable'          },
  { value: 'earthing',           label: 'Earthing'          },
  { value: 'meter',              label: 'Meter'             },
  { value: 'installation',       label: 'Installation'      },
  { value: 'others',             label: 'Others'            },
];

export const VALID_CATEGORIES = new Set<string>(CATEGORIES.map((c) => c.value));

/**
 * GST rates per category — post 56th GST Council (Sep 2025)
 * PV Modules & on-grid Inverters: 5%
 * All other equipment, cables, boards, earthing, meter: 18%
 * Installation (EPC service): 18%
 */
export const CATEGORY_GST: Record<Category, number> = {
  'pv-modules':         5,
  'inverters':          5,
  'mounting-structure': 18,
  'dc-db':              18,
  'ac-db':              18,
  'dc-cable':           18,
  'ac-cable':           18,
  'earthing':           18,
  'meter':              18,
  'installation':       18,
  'others':             18,
};

export const CATEGORY_COLORS: Record<Category, string> = {
  'pv-modules':         'bg-sky-50 text-sky-700 border-sky-200',
  'inverters':          'bg-yellow-50 text-yellow-700 border-yellow-200',
  'mounting-structure': 'bg-slate-100 text-slate-600 border-slate-300',
  'dc-db':              'bg-orange-50 text-orange-700 border-orange-200',
  'ac-db':              'bg-red-50 text-red-700 border-red-200',
  'dc-cable':           'bg-amber-50 text-amber-700 border-amber-200',
  'ac-cable':           'bg-lime-50 text-lime-700 border-lime-200',
  'earthing':           'bg-emerald-50 text-emerald-700 border-emerald-200',
  'meter':              'bg-violet-50 text-violet-700 border-violet-200',
  'installation':       'bg-blue-50 text-blue-700 border-blue-200',
  'others':             'bg-gray-100 text-gray-600 border-gray-300',
};

export const SHEETS_STORAGE_KEY   = 'rayenna_costing_sheets_v1';
export const BOM_FROM_COSTING_KEY = 'rayenna_bom_from_costing_v1';
export const ROI_AUTOFILL_KEY     = 'rayenna_roi_autofill_v1';

export interface RoiAutofill {
  source:        'costing-sheet' | 'bom';
  sourceName:    string;
  savedAt:       string;
  grandTotal:    number;
  systemSizeKw:  number;
}

export interface SavedSheet {
  id:            string;
  name:          string;
  description:   string;
  savedAt:       string;
  items:         LineItem[];
  showGst:       boolean;
  marginPercent: number;
  grandTotal:    number;
  systemSizeKw:  number;
}

export interface LineItem {
  category:      Category;
  itemName:      string;
  specification: string;
  quantity:      string;
  unitCost:      string;
  gstPercent:    string;
}

export interface BomRowGenerated {
  category:        Category;
  itemName:        string;
  specification:   string;
  quantity:        string;
  brand:           string;
  isAutoGenerated: boolean;
}

export interface StoredBom {
  sheetId:       string;
  sheetName:     string;
  generatedAt:   string;
  rows:          BomRowGenerated[];
}

export const DEFAULT_MARGIN = 15;

export const CATEGORY_DEFAULTS: Record<Category, { specification: string }> = {
  'pv-modules':         { specification: 'As per datasheet'         },
  'inverters':          { specification: 'As per datasheet'         },
  'mounting-structure': { specification: 'Hot-dip galvanised MS/GI' },
  'dc-db':              { specification: 'IP65, MCB + SPD Type II'  },
  'ac-db':              { specification: 'IP65, MCCB + SPD + RCCB' },
  'dc-cable':           { specification: 'UV-resistant, 1500V DC'   },
  'ac-cable':           { specification: 'XLPE, 1100V AC'           },
  'earthing':           { specification: 'As per IS 3043'           },
  'meter':              { specification: 'DISCOM-approved'          },
  'installation':       { specification: 'EPC turnkey'              },
  'others':             { specification: ''                         },
};

/** Snap a raw category string to the nearest valid Category value */
export function snapCategory(raw: string, itemName = ''): Category {
  const s    = raw.toLowerCase().trim().replace(/[\s_]+/g, '-');
  const item = itemName.toLowerCase();

  // Exact match first (handles all new keys like ac-db, dc-cable, etc.)
  if (VALID_CATEGORIES.has(s)) return s as Category;

  // Legacy key aliases
  if (s === 'module' || s === 'panel' || s === 'pv' || s === 'solar')
    return 'pv-modules';
  if (s === 'inverter' || s === 'pcb' || s === 'vfd')
    return 'inverters';
  if (s === 'structure' || s === 'struct' || s === 'mounting' || s === 'mount')
    return 'mounting-structure';
  if (s === 'labour' || s === 'labor' || s === 'transport' || s === 'transportation')
    return 'installation';

  // For the old "electrical" catch-all: classify by item name keywords
  if (s === 'electrical' || s === 'elec') {
    // DC Distribution Board
    if (item.includes('dcdb') || (item.includes('dc') && item.includes('db')))
      return 'dc-db';
    // AC Distribution Board — isolators also belong here
    if (item.includes('acdb') || (item.includes('ac') && item.includes('db')) ||
        item.includes('isolator') || item.includes('mccb') || item.includes('rccb') || item.includes('mcb'))
      return 'ac-db';
    // Earthing — bare copper, copper bonded, earth rod, earth chamber, lightning
    if (item.includes('earth') || item.includes('lightning') || item.includes('arrestor') ||
        item.includes('bare copper') || item.includes('copper bonded') || item.includes('copper rod') ||
        item.includes('earth chamber') || item.includes('earth compound') ||
        item.includes('terminal strip') || item.includes('earth bench') || item.includes('swg'))
      return 'earthing';
    // Meter
    if (item.includes('meter') || item.includes('discom') || item.includes('meter box') ||
        item.includes('unidirection') || item.includes('bidirection'))
      return 'meter';
    // DC Cable (MC4, DC cable explicitly)
    if (item.includes('mc4') || (item.includes('dc') && item.includes('cable')))
      return 'dc-cable';
    // AC Cable
    if (item.includes('ac') && item.includes('cable'))
      return 'ac-cable';
    // Generic cable / conduit fittings / fasteners / accessories → dc-cable
    if (item.includes('cable') || item.includes('wire') || item.includes('pvc') ||
        item.includes('conduit') || item.includes('pipe') || item.includes('clamp') ||
        item.includes('lug') || item.includes('cable tie') || item.includes('insulation') ||
        item.includes('bend') || item.includes('tee') || item.includes('elbow') ||
        item.includes('coupling') || item.includes('flexible') || item.includes('hose') ||
        item.includes('screw') || item.includes('fisher') || item.includes('sleeve') ||
        item.includes('mid clamp') || item.includes('end clamp') || item.includes('sqmm') ||
        item.includes('channel') || item.includes('tray'))
      return 'dc-cable';
    return 'others';
  }

  // Fuzzy keyword matching on the category string itself
  if (s.includes('pv') || s.includes('module') || s.includes('panel') || s.includes('solar'))
    return 'pv-modules';
  if (s.includes('inverter') || s.includes('pcb') || s.includes('vfd'))
    return 'inverters';
  if (s.includes('struct') || s.includes('mount') || s.includes('frame') || s.includes('rack'))
    return 'mounting-structure';
  if ((s.includes('dc') && s.includes('db')) || s.includes('dc-dist') || s.includes('dcdb'))
    return 'dc-db';
  if ((s.includes('ac') && s.includes('db')) || s.includes('ac-dist') || s.includes('acdb'))
    return 'ac-db';
  if (s.includes('dc') && (s.includes('cable') || s.includes('wire')))
    return 'dc-cable';
  if (s.includes('ac') && (s.includes('cable') || s.includes('wire')))
    return 'ac-cable';
  if (s.includes('cable') || s.includes('wire') || s.includes('conduit') || s.includes('mc4'))
    return 'dc-cable';
  if (s.includes('earth') || s.includes('lightning') || s.includes('arrestor'))
    return 'earthing';
  if (s.includes('meter') || s.includes('discom') || s.includes('net-meter'))
    return 'meter';
  if (s.includes('install') || s.includes('labour') || s.includes('labor') ||
      s.includes('commission') || s.includes('transport'))
    return 'installation';
  return 'others';
}

/** Derive system size (kW) from module-category items */
export function deriveSystemSizeKw(items: LineItem[]): number {
  const modules = items.filter((r) => r.category === 'pv-modules');
  let totalWatts = 0;
  for (const m of modules) {
    const qty = parseFloat(m.quantity) || 0;
    const match = m.itemName.match(/(\d+(?:\.\d+)?)\s*[Ww][Pp]?/);
    if (match) {
      totalWatts += qty * parseFloat(match[1]);
    }
  }
  return totalWatts > 0 ? Math.round((totalWatts / 1000) * 100) / 100 : 0;
}

export function sheetGrandTotal(items: LineItem[], inclGst: boolean, marginPct = DEFAULT_MARGIN): number {
  const toNum = (v: string) => parseFloat(v) || 0;
  const base = items.reduce((s, r) => s + toNum(r.quantity) * toNum(r.unitCost), 0);
  const gst  = inclGst
    ? items.reduce((s, r) => {
        const b = toNum(r.quantity) * toNum(r.unitCost);
        return s + b * (toNum(r.gstPercent) / 100);
      }, 0)
    : 0;
  const subtotal = base + gst;
  return subtotal + subtotal * (marginPct / 100);
}

export function costingToBom(items: LineItem[]): BomRowGenerated[] {
  const map = new Map<string, BomRowGenerated>();
  items
    .filter((r) => r.itemName.trim())
    .forEach((r) => {
      const key = `${r.category}||${r.itemName.trim().toLowerCase()}`;
      if (map.has(key)) {
        const existing = map.get(key)!;
        existing.quantity = String(parseFloat(existing.quantity) + (parseFloat(r.quantity) || 0));
        if (r.specification?.trim() && !existing.specification) {
          existing.specification = r.specification.trim();
        }
      } else {
        const defaults = CATEGORY_DEFAULTS[r.category] ?? CATEGORY_DEFAULTS['others'];
        const spec = r.specification?.trim() || defaults.specification;
        map.set(key, {
          category:        r.category,
          itemName:        r.itemName.trim(),
          specification:   spec,
          quantity:        r.quantity || '0',
          brand:           '',
          isAutoGenerated: true,
        });
      }
    });
  return Array.from(map.values());
}

export function catAccentColor(catValue: string): string {
  const map: Record<string, string> = {
    'pv-modules':         '#0369a1',
    'inverters':          '#b45309',
    'mounting-structure': '#475569',
    'dc-db':              '#c2410c',
    'ac-db':              '#b91c1c',
    'dc-cable':           '#d97706',
    'ac-cable':           '#65a30d',
    'earthing':           '#059669',
    'meter':              '#7c3aed',
    'installation':       '#1d4ed8',
    'others':             '#6b7280',
  };
  return map[catValue] ?? '#6b7280';
}
