import { CATEGORY_GST } from '../lib/costingConstants';
import type { LineItem } from '../lib/costingConstants';
import type { CostingTemplate } from './types';
import { toNum } from './format';

export const EMPTY_ROW: LineItem = {
  category:      'pv-modules',
  itemName:      '',
  specification: '',
  quantity:      '',
  unitCost:      '',
  gstPercent:    String(CATEGORY_GST['pv-modules']),
};

/** Six Rayenna production templates — converted directly from actual project Excel files */
export const BUILT_IN_TEMPLATES: CostingTemplate[] = [
  // ── 1. 3KW DCR ──────────────────────────────────────────────────────────────
  {
    id: 'builtin_3kw_dcr',
    name: '3KW DCR',
    description: '3 kW On-Grid Residential — DCR (Domestic Content Requirement)',
    savedAt: '2025-01-01T00:00:00.000Z',
    isBuiltIn: true,
    items: [
      { category: 'pv-modules',         itemName: 'TopCon Module',                              specification: 'ADANI 600-620 DCR TOPCON MODULE',                          quantity: '5',   unitCost: '17050', gstPercent: '5'  },
      { category: 'inverters',          itemName: '3kW String Inverter',                        specification: 'SOLAR GRID TIED STRING INVERTER-3KW 1PH MAKE:SUNWAYS/DEYE/SOLAIRE', quantity: '1', unitCost: '19000', gstPercent: '5'  },
      { category: 'ac-db',              itemName: '1-5KW 1PH ACDB',                             specification: '1-5KW 1PH ACDB PREMIUM HAVELLS',                           quantity: '1',   unitCost: '1400',  gstPercent: '18' },
      { category: 'dc-db',              itemName: '1-5KW 1IN 1OUT DCDB',                        specification: '1-5KW 1IN 1OUT DCDB PREMIUM HAVELLS',                      quantity: '1',   unitCost: '1600',  gstPercent: '18' },
      { category: 'dc-cable',           itemName: 'DC Cable',                                   specification: '4SQMM DC CABLE POLYCAB',                                   quantity: '90',  unitCost: '41',    gstPercent: '18' },
      { category: 'ac-cable',           itemName: 'AC Cable',                                   specification: '4SQMM AC CU CABLE HAVELLS',                                quantity: '30',  unitCost: '43',    gstPercent: '18' },
      { category: 'earthing',           itemName: 'MC4 Connectors (pair)',                      specification: 'MC4 CONNECTORS SIBASS',                                    quantity: '6',   unitCost: '35',    gstPercent: '18' },
      { category: 'earthing',           itemName: 'Bare Copper 10SWG',                          specification: 'BARE COPPER 10SWG',                                        quantity: '70',  unitCost: '110',   gstPercent: '18' },
      { category: 'earthing',           itemName: 'Copper Bonded Rod 4ft',                      specification: 'COPPER BONDED ROD 4FT EXCEL',                              quantity: '3',   unitCost: '310',   gstPercent: '18' },
      { category: 'earthing',           itemName: 'Earth Chamber',                              specification: 'EARTH CHAMBER EXCEL',                                     quantity: '3',   unitCost: '300',   gstPercent: '18' },
      { category: 'earthing',           itemName: 'Earth Compound 10 KG',                       specification: 'EARTH COMPOUND 10 KG EXCEL',                               quantity: '1',   unitCost: '200',   gstPercent: '18' },
      { category: 'earthing',           itemName: 'SS Terminal Strip / Earth Bench 4 Pole',     specification: 'SS TERMINAL STRIP/EARTH BENCH 4POLE EXCEL',                quantity: '1',   unitCost: '200',   gstPercent: '18' },
      { category: 'earthing',           itemName: 'PVC Channel 45*45 Cable Tray',               specification: 'PVC CHANNEL 45*45 CABLE TRAY',                             quantity: '3',   unitCost: '100',   gstPercent: '18' },
      { category: 'earthing',           itemName: 'Lightning Arrestor Single Spike',            specification: 'LIGHTNING ARRESTER SINGLE SPIKE EXCEL',                    quantity: '1',   unitCost: '650',   gstPercent: '18' },
      { category: 'meter',              itemName: 'Meter Box 1PH',                              specification: 'METER BOX 1PH',                                            quantity: '1',   unitCost: '600',   gstPercent: '18' },
      { category: 'meter',              itemName: 'AC Isolator 40A 2P',                         specification: 'AC ISOLATOR 40A 2P HAVELLS',                               quantity: '1',   unitCost: '250',   gstPercent: '18' },
      { category: 'meter',              itemName: '1PH Unidirectional Meter',                   specification: '1PH UNIDIRECTION METER GENUS/VISIONTEK',                   quantity: '1',   unitCost: '1500',  gstPercent: '18' },
      { category: 'mounting-structure', itemName: '20MM ISI Light PVC Pipe Ivory',              specification: '20MM ISI LIGHT PVC PIPE IVORY',                            quantity: '30',  unitCost: '50',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: '20MM Bend Ivory',                            specification: '20MM BEND IVORY',                                          quantity: '25',  unitCost: '7',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: '20MM Tee Ivory',                             specification: '20MM TEE IVORY',                                           quantity: '5',   unitCost: '7',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: '20MM Elbow Ivory',                           specification: '20MM ELBOW IVORY',                                         quantity: '25',  unitCost: '7',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: '20MM Coupling Ivory',                        specification: '20MM COUPLING IVORY',                                      quantity: '5',   unitCost: '7',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: '20MM Flexible Hose Ivory',                   specification: '20MM FLEXIBLE HOSE IVORY',                                 quantity: '3',   unitCost: '12',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: '20MM SS Clamp',                              specification: '20MM SS CLAMP',                                            quantity: '150', unitCost: '4',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: '6MM Plastic Sleeve',                         specification: '6MM PLASTIC SLEEVE',                                       quantity: '3',   unitCost: '7',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Fisher 6MM',                                 specification: 'FISHER 6MM',                                               quantity: '200', unitCost: '1',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Self Taping Screw 6*38 SS',                  specification: 'SELF TAPING SCREW 6*38 SS(1.5")',                          quantity: '50',  unitCost: '1.5',   gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Self Taping Screw 6*25 SS',                  specification: 'SELF TAPING SCREW 6*25 SS(1")',                            quantity: '150', unitCost: '1',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: '35MM Mid Clamp',                             specification: '35MM MID CLAMP',                                           quantity: '10',  unitCost: '20',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: '35MM End Clamp',                             specification: '35MM END CLAMP',                                           quantity: '10',  unitCost: '20',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Insulation Tape Red/Black/Green',            specification: 'INSULATION TAPE RED/BLACK/GREEN',                          quantity: '3',   unitCost: '10',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: '20MM Cycle Screw with Washer',               specification: '20MM CYCLE SCREW WITH WASHER',                             quantity: '10',  unitCost: '1',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: '4-6 SQMM CU Ring Lug',                       specification: '4-6 SQMM CU RING LUG',                                     quantity: '20',  unitCost: '4.8',   gstPercent: '18' },
      { category: 'mounting-structure', itemName: '370*4.6 Cable Tie',                          specification: '370*4.6 CABLE TIE',                                        quantity: '100', unitCost: '2',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Base Plate 4*4',                             specification: 'BASE PLATE 4*4',                                           quantity: '1',   unitCost: '60',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Anchor Bolt 8MM',                            specification: 'ANCHOR BOLT 8MM',                                          quantity: '10',  unitCost: '10',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Cutting Wheel',                              specification: 'CUTTING WHEEL',                                            quantity: '7',   unitCost: '20',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Amcos Epoxy Primer Grey 1 Ltr',              specification: 'AMCOS EPOXY PRIMER GREY 1 LTR',                            quantity: '2',   unitCost: '400',   gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Sheenlac Thinner D13 1 Ltr',                 specification: 'SHEENLAC THINNER D13*1 LTR',                               quantity: '2',   unitCost: '200',   gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'GP Pipes 3*1.5',                             specification: 'GP PIPES 3*1.5',                                           quantity: '3',   unitCost: '1146',  gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'GP Pipes 1.5*1.5',                           specification: 'GP PIPES 1.5*1.5',                                         quantity: '3',   unitCost: '750',   gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'End Cap 3*1.5',                              specification: 'END CAP-3*1.5',                                            quantity: '40',  unitCost: '10',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Welding Rod 12 Gauge',                       specification: 'WELDING ROD 12 GUAGE',                                     quantity: '1',   unitCost: '400',   gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Sliding Door 4*4',                           specification: "SLIDING DOOR 4*4'",                                        quantity: '1',   unitCost: '4000',  gstPercent: '18' },
      { category: 'others',             itemName: 'Miscellaneous',                              specification: 'MISCELLANEOUS',                                            quantity: '1',   unitCost: '1000',  gstPercent: '18' },
      { category: 'installation',       itemName: 'Structure Labour',                           specification: 'STRUCTURE LABOUR',                                         quantity: '3',   unitCost: '4000',  gstPercent: '18' },
      { category: 'installation',       itemName: 'Electrical Labour',                          specification: 'ELECTRICAL LABOUR',                                        quantity: '3',   unitCost: '2000',  gstPercent: '18' },
      { category: 'installation',       itemName: 'Transportation',                             specification: 'TRANSPORTATION',                                           quantity: '70',  unitCost: '40',    gstPercent: '18' },
      { category: 'installation',       itemName: 'Unloading',                                  specification: 'UNLOADING',                                                quantity: '1',   unitCost: '600',   gstPercent: '18' },
      { category: 'others',             itemName: 'KSEB Liasoning',                             specification: 'KSEB Liasoning and other work',                            quantity: '1',   unitCost: '1000',  gstPercent: '18' },
      { category: 'installation',       itemName: 'Travel Expenses',                            specification: 'TRAVEL EXPENSES',                                          quantity: '1',   unitCost: '2000',  gstPercent: '18' },
      { category: 'installation',       itemName: 'Electrical Contractor',                      specification: 'ELECTRICAL CONTRACTOR',                                    quantity: '1',   unitCost: '1000',  gstPercent: '18' },
    ],
  },

  // ── 2. 5KW DCR ──────────────────────────────────────────────────────────────
  {
    id: 'builtin_5kw_dcr',
    name: '5KW DCR',
    description: '5 kW On-Grid Residential — DCR (Domestic Content Requirement)',
    savedAt: '2025-01-01T00:00:00.000Z',
    isBuiltIn: true,
    items: [
      { category: 'pv-modules',         itemName: 'TopCon Module',                              specification: 'ADANI 620DCR TOPCON MODULE',                                quantity: '8',   unitCost: '17360', gstPercent: '5'  },
      { category: 'inverters',          itemName: '5kW String Inverter',                        specification: 'SOLAR GRID TIED STRING INVERTER-5KW 1PH MAKE:DEYE/GROWATT', quantity: '1',   unitCost: '27000', gstPercent: '5'  },
      { category: 'ac-db',              itemName: '1-5KW 1PH ACDB',                             specification: '1-5KW 1PH ACDB PREMIUM HAVELLS',                           quantity: '1',   unitCost: '1400',  gstPercent: '18' },
      { category: 'dc-db',              itemName: '1-5KW 2IN 2OUT DCDB',                        specification: '1-5KW 2IN 2OUT DCDB PREMIUM HAVELLS',                      quantity: '1',   unitCost: '3000',  gstPercent: '18' },
      { category: 'dc-cable',           itemName: '4SQMM DC Cable Polycab',                     specification: '4SQMM DC CABLE POLYCAB',                                   quantity: '120', unitCost: '41',    gstPercent: '18' },
      { category: 'ac-cable',           itemName: '6SQMM AC CU Cable Havells',                  specification: '6SQMM AC CU CABLE HAVELLS',                                quantity: '30',  unitCost: '67',    gstPercent: '18' },
      { category: 'earthing',           itemName: 'MC4 Connectors',                             specification: 'MC4 CONNECTORS SIBASS',                                    quantity: '10',  unitCost: '35',    gstPercent: '18' },
      { category: 'earthing',           itemName: 'Bare Copper 10SWG',                          specification: 'BARE COPPER 10SWG',                                        quantity: '80',  unitCost: '115',   gstPercent: '18' },
      { category: 'earthing',           itemName: 'Copper Bonded Rod 4ft',                      specification: 'COPPER BONDED ROD 4FT EXCEL',                              quantity: '3',   unitCost: '300',   gstPercent: '18' },
      { category: 'earthing',           itemName: 'Earth Chamber',                              specification: 'EARTH CHAMBER EXCEL',                                     quantity: '3',   unitCost: '300',   gstPercent: '18' },
      { category: 'earthing',           itemName: 'Earth Compound 10 KG',                       specification: 'EARTH COMPOUND 10 KG EXCEL',                               quantity: '1',   unitCost: '200',   gstPercent: '18' },
      { category: 'earthing',           itemName: 'SS Terminal Strip / Earth Bench 4 Pole',     specification: 'SS TERMINAL STRIP/EARTH BENCH 4POLE EXCEL',                quantity: '1',   unitCost: '200',   gstPercent: '18' },
      { category: 'earthing',           itemName: 'PVC Channel 45*45 Cable Tray',               specification: 'PVC CHANNEL 45*45 CABLE TRAY',                             quantity: '3',   unitCost: '100',   gstPercent: '18' },
      { category: 'earthing',           itemName: 'Lightning Arrestor Single Spike',            specification: 'LIGHTNING ARRESTER SINGLE SPIKE EXCEL',                    quantity: '1',   unitCost: '650',   gstPercent: '18' },
      { category: 'meter',              itemName: 'Meter Box 1PH',                              specification: 'METER BOX 1PH',                                            quantity: '1',   unitCost: '600',   gstPercent: '18' },
      { category: 'meter',              itemName: 'AC Isolator 40A 2P',                         specification: 'AC ISOLATOR 40A 2P HAVELLS',                               quantity: '1',   unitCost: '250',   gstPercent: '18' },
      { category: 'meter',              itemName: '1PH Unidirectional Meter',                   specification: '1PH UNIDIRECTION METER GENUS/VISIONTEK',                   quantity: '1',   unitCost: '1500',  gstPercent: '18' },
      { category: 'mounting-structure', itemName: '25MM ISI Light PVC Pipe Ivory',              specification: '25MM ISI LIGHT PVC PIPE IVORY',                            quantity: '25',  unitCost: '70',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: '25MM Bend Ivory',                            specification: '25MM BEND IVORY',                                          quantity: '20',  unitCost: '8',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: '25MM Tee Ivory',                             specification: '25MM TEE IVORY',                                           quantity: '5',   unitCost: '8',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: '25MM Elbow Ivory',                           specification: '25MM ELBOW IVORY',                                         quantity: '25',  unitCost: '8',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: '25MM Coupling Ivory',                        specification: '25MM COUPLING IVORY',                                      quantity: '5',   unitCost: '8',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: '25MM Flexible Hose Ivory',                   specification: '25MM FLEXIBLE HOSE IVORY',                                 quantity: '3',   unitCost: '10',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: '25MM SS Clamp',                              specification: '25MM SS CLAMP',                                            quantity: '150', unitCost: '5',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: '6MM Plastic Sleeve',                         specification: '6MM PLASTIC SLEEVE',                                       quantity: '3',   unitCost: '7',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Fisher 6MM',                                 specification: 'FISHER 6MM',                                               quantity: '200', unitCost: '1',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Self Taping Screw 6*38 SS',                  specification: 'SELF TAPING SCREW 6*38 SS(1.5")',                          quantity: '50',  unitCost: '1.5',   gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Self Taping Screw 6*25 SS',                  specification: 'SELF TAPING SCREW 6*25 SS(1")',                            quantity: '150', unitCost: '1',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: '35MM Mid Clamp',                             specification: '35MM MID CLAMP',                                           quantity: '10',  unitCost: '20',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: '35MM End Clamp',                             specification: '35MM END CLAMP',                                           quantity: '10',  unitCost: '20',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Insulation Tape Red/Black/Green',            specification: 'INSULATION TAPE RED/BLACK/GREEN',                          quantity: '3',   unitCost: '10',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: '20MM Cycle Screw with Washer',               specification: '20MM CYCLE SCREW WITH WASHER',                             quantity: '10',  unitCost: '1',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: '4-6 SQMM CU Ring Lug',                       specification: '4-6 SQMM CU RING LUG',                                     quantity: '20',  unitCost: '4.8',   gstPercent: '18' },
      { category: 'mounting-structure', itemName: '370*4.6 Cable Tie',                          specification: '370*4.6 CABLE TIE',                                        quantity: '100', unitCost: '2',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Base Plate 4*4',                             specification: 'BASE PLATE 4*4',                                           quantity: '11',  unitCost: '60',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Anchor Bolt 8MM',                            specification: 'ANCHOR BOLT 8MM',                                          quantity: '45',  unitCost: '10',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Cutting Wheel',                              specification: 'CUTTING WHEEL',                                            quantity: '7',   unitCost: '20',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Amcos Epoxy Primer Grey 1 Ltr',              specification: 'AMCOS EPOXY PRIMER GREY 1 LTR',                            quantity: '2',   unitCost: '400',   gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Sheenlac Thinner D13 1 Ltr',                 specification: 'SHEENLAC THINNER D13*1 LTR',                               quantity: '2',   unitCost: '200',   gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'GP Pipes 3*1.5',                             specification: 'GP PIPES 3*1.5',                                           quantity: '5',   unitCost: '1300',  gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'GP Pipes 1.5*1.5',                           specification: 'GP PIPES 1.5*1.5',                                         quantity: '4',   unitCost: '750',   gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'End Cap 2x2',                                specification: 'END CAP-2x2',                                              quantity: '30',  unitCost: '10',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Welding Rod 12 Gauge',                       specification: 'WELDING ROD 12 GUAGE',                                     quantity: '1',   unitCost: '400',   gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Sliding Door 4*4',                           specification: "SLIDING DOOR 4*4'",                                        quantity: '1',   unitCost: '4000',  gstPercent: '18' },
      { category: 'others',             itemName: 'Miscellaneous',                              specification: 'MISCELLANEOUS',                                            quantity: '1',   unitCost: '2500',  gstPercent: '18' },
      { category: 'installation',       itemName: 'Structure Labour',                           specification: 'STRUCTURE LABOUR',                                         quantity: '5',   unitCost: '3500',  gstPercent: '18' },
      { category: 'installation',       itemName: 'Electrical Labour',                          specification: 'ELECTRICAL LABOUR',                                        quantity: '5',   unitCost: '1500',  gstPercent: '18' },
      { category: 'installation',       itemName: 'Transportation',                             specification: 'TRANSPORTATION',                                           quantity: '100', unitCost: '40',    gstPercent: '18' },
      { category: 'installation',       itemName: 'Unloading',                                  specification: 'UNLOADING',                                                quantity: '1',   unitCost: '600',   gstPercent: '18' },
      { category: 'others',             itemName: 'KSEB Liasoning',                             specification: 'KSEB Liasoning',                                           quantity: '1',   unitCost: '2000',  gstPercent: '18' },
      { category: 'installation',       itemName: 'Travel Expenses',                            specification: 'TRAVEL EXPENSES',                                          quantity: '1',   unitCost: '1500',  gstPercent: '18' },
      { category: 'installation',       itemName: 'Electrical Contractor',                      specification: 'ELECTRICAL CONTRACTOR',                                    quantity: '1',   unitCost: '1000',  gstPercent: '18' },
    ],
  },

  // ── 3. 5KW Non DCR ──────────────────────────────────────────────────────────
  {
    id: 'builtin_5kw_nondcr',
    name: '5KW Non DCR',
    description: '5 kW On-Grid Residential — Non-DCR',
    savedAt: '2025-01-01T00:00:00.000Z',
    isBuiltIn: true,
    items: [
      { category: 'pv-modules',         itemName: 'TopCon Module',                              specification: 'WAAREE 590NDCR TOPCON MODULE',                              quantity: '9',   unitCost: '10620', gstPercent: '5'  },
      { category: 'inverters',          itemName: '5kW String Inverter',                        specification: 'SOLAR GRID TIED STRING INVERTER-5KW 1PH MAKE:DEYE/GROWATT', quantity: '1',   unitCost: '28000', gstPercent: '5'  },
      { category: 'ac-db',              itemName: '1-5KW 1PH ACDB',                             specification: '1-5KW 1PH ACDB PREMIUM HAVELLS',                           quantity: '1',   unitCost: '1400',  gstPercent: '18' },
      { category: 'dc-db',              itemName: '1-5KW 2IN 2OUT DCDB',                        specification: '1-5KW 2IN 2OUT DCDB PREMIUM HAVELLS',                      quantity: '1',   unitCost: '3000',  gstPercent: '18' },
      { category: 'dc-cable',           itemName: '4SQMM DC Cable Polycab',                     specification: '4SQMM DC CABLE POLYCAB',                                   quantity: '180', unitCost: '41',    gstPercent: '18' },
      { category: 'ac-cable',           itemName: '16SQMM AC AL Cable Havells',                 specification: '16SQMM AC AL CABLE HAVELLS',                               quantity: '45',  unitCost: '106',   gstPercent: '18' },
      { category: 'earthing',           itemName: 'MC4 Connectors',                             specification: 'MC4 CONNECTORS SIBASS',                                    quantity: '10',  unitCost: '35',    gstPercent: '18' },
      { category: 'earthing',           itemName: 'Bare Copper 10SWG',                          specification: 'BARE COPPER 10SWG',                                        quantity: '120', unitCost: '140',   gstPercent: '18' },
      { category: 'earthing',           itemName: 'Copper Bonded Rod 4ft',                      specification: 'COPPER BONDED ROD 4FT EXCEL',                              quantity: '3',   unitCost: '300',   gstPercent: '18' },
      { category: 'earthing',           itemName: 'Earth Chamber',                              specification: 'EARTH CHAMBER EXCEL',                                     quantity: '3',   unitCost: '300',   gstPercent: '18' },
      { category: 'earthing',           itemName: 'Earth Compound 10 KG',                       specification: 'EARTH COMPOUND 10 KG EXCEL',                               quantity: '1',   unitCost: '200',   gstPercent: '18' },
      { category: 'earthing',           itemName: 'SS Terminal Strip / Earth Bench 4 Pole',     specification: 'SS TERMINAL STRIP/EARTH BENCH 4POLE EXCEL',                quantity: '1',   unitCost: '200',   gstPercent: '18' },
      { category: 'earthing',           itemName: 'PVC Channel 45*45 Cable Tray',               specification: 'PVC CHANNEL 45*45 CABLE TRAY',                             quantity: '3',   unitCost: '100',   gstPercent: '18' },
      { category: 'earthing',           itemName: 'Lightning Arrestor Single Spike',            specification: 'LIGHTNING ARRESTER SINGLE SPIKE EXCEL',                    quantity: '1',   unitCost: '650',   gstPercent: '18' },
      { category: 'meter',              itemName: 'Meter Box 1PH',                              specification: 'METER BOX 1PH',                                            quantity: '1',   unitCost: '600',   gstPercent: '18' },
      { category: 'meter',              itemName: 'AC Isolator 40A 2P',                         specification: 'AC ISOLATOR 40A 2P HAVELLS',                               quantity: '1',   unitCost: '250',   gstPercent: '18' },
      { category: 'meter',              itemName: '1PH Unidirectional Meter',                   specification: '1PH UNIDIRECTION METER GENUS/VISIONTEK',                   quantity: '1',   unitCost: '1500',  gstPercent: '18' },
      { category: 'mounting-structure', itemName: '25MM ISI Light PVC Pipe Ivory',              specification: '25MM ISI LIGHT PVC PIPE IVORY',                            quantity: '30',  unitCost: '70',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: '25MM Bend Ivory',                            specification: '25MM BEND IVORY',                                          quantity: '25',  unitCost: '8',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: '25MM Tee Ivory',                             specification: '25MM TEE IVORY',                                           quantity: '5',   unitCost: '8',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: '25MM Elbow Ivory',                           specification: '25MM ELBOW IVORY',                                         quantity: '25',  unitCost: '8',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: '25MM Coupling Ivory',                        specification: '25MM COUPLING IVORY',                                      quantity: '5',   unitCost: '8',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: '25MM Flexible Hose Ivory',                   specification: '25MM FLEXIBLE HOSE IVORY',                                 quantity: '3',   unitCost: '10',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: '25MM SS Clamp',                              specification: '25MM SS CLAMP',                                            quantity: '150', unitCost: '5',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: '6MM Plastic Sleeve',                         specification: '6MM PLASTIC SLEEVE',                                       quantity: '3',   unitCost: '7',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Fisher 6MM',                                 specification: 'FISHER 6MM',                                               quantity: '200', unitCost: '1',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Self Taping Screw 6*38 SS',                  specification: 'SELF TAPING SCREW 6*38 SS(1.5")',                          quantity: '50',  unitCost: '1.5',   gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Self Taping Screw 6*25 SS',                  specification: 'SELF TAPING SCREW 6*25 SS(1")',                            quantity: '150', unitCost: '1',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: '35MM Mid Clamp',                             specification: '35MM MID CLAMP',                                           quantity: '10',  unitCost: '20',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: '35MM End Clamp',                             specification: '35MM END CLAMP',                                           quantity: '10',  unitCost: '20',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Insulation Tape Red/Black/Green',            specification: 'INSULATION TAPE RED/BLACK/GREEN',                          quantity: '3',   unitCost: '10',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: '20MM Cycle Screw with Washer',               specification: '20MM CYCLE SCREW WITH WASHER',                             quantity: '10',  unitCost: '1',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: '4-6 SQMM CU Ring Lug',                       specification: '4-6 SQMM CU RING LUG',                                     quantity: '20',  unitCost: '4.8',   gstPercent: '18' },
      { category: 'mounting-structure', itemName: '370*4.6 Cable Tie',                          specification: '370*4.6 CABLE TIE',                                        quantity: '100', unitCost: '2',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Base Plate 4*4',                             specification: 'BASE PLATE 4*4',                                           quantity: '11',  unitCost: '60',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Anchor Bolt 8MM',                            specification: 'ANCHOR BOLT 8MM',                                          quantity: '45',  unitCost: '10',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Cutting Wheel',                              specification: 'CUTTING WHEEL',                                            quantity: '7',   unitCost: '20',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Amcos Epoxy Primer Grey 1 Ltr',              specification: 'AMCOS EPOXY PRIMER GREY 1 LTR',                            quantity: '2',   unitCost: '400',   gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Sheenlac Thinner D13 1 Ltr',                 specification: 'SHEENLAC THINNER D13*1 LTR',                               quantity: '2',   unitCost: '200',   gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'GP Pipes 3*1.5',                             specification: 'GP PIPES 3*1.5',                                           quantity: '5',   unitCost: '1300',  gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'GP Pipes 1.5*1.5',                           specification: 'GP PIPES 1.5*1.5',                                         quantity: '4',   unitCost: '750',   gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'End Cap 2x2',                                specification: 'END CAP-2x2',                                              quantity: '30',  unitCost: '10',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Welding Rod 12 Gauge',                       specification: 'WELDING ROD 12 GUAGE',                                     quantity: '1',   unitCost: '400',   gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Sliding Door 4*4',                           specification: "SLIDING DOOR 4*4'",                                        quantity: '1',   unitCost: '4000',  gstPercent: '18' },
      { category: 'others',             itemName: 'Miscellaneous',                              specification: 'MISCELLANEOUS',                                            quantity: '1',   unitCost: '2500',  gstPercent: '18' },
      { category: 'installation',       itemName: 'Structure Labour',                           specification: 'STRUCTURE LABOUR',                                         quantity: '5',   unitCost: '3500',  gstPercent: '18' },
      { category: 'installation',       itemName: 'Electrical Labour',                          specification: 'ELECTRICAL LABOUR',                                        quantity: '5',   unitCost: '1500',  gstPercent: '18' },
      { category: 'installation',       itemName: 'Transportation',                             specification: 'TRANSPORTATION',                                           quantity: '100', unitCost: '40',    gstPercent: '18' },
      { category: 'installation',       itemName: 'Unloading',                                  specification: 'UNLOADING',                                                quantity: '1',   unitCost: '600',   gstPercent: '18' },
      { category: 'others',             itemName: 'KSEB Liasoning',                             specification: 'KSEB Liasoning',                                           quantity: '1',   unitCost: '2000',  gstPercent: '18' },
      { category: 'installation',       itemName: 'Travel Expenses',                            specification: 'TRAVEL EXPENSES',                                          quantity: '1',   unitCost: '1500',  gstPercent: '18' },
      { category: 'installation',       itemName: 'Electrical Contractor',                      specification: 'ELECTRICAL CONTRACTOR',                                    quantity: '1',   unitCost: '1000',  gstPercent: '18' },
    ],
  },

  // ── 4. 10KW Non DCR ─────────────────────────────────────────────────────────
  {
    id: 'builtin_10kw_nondcr',
    name: '10KW Non DCR',
    description: '10 kW On-Grid Commercial — Non-DCR',
    savedAt: '2025-01-01T00:00:00.000Z',
    isBuiltIn: true,
    items: [
      { category: 'pv-modules',         itemName: 'TopCon Module',                              specification: 'WAAREE 590NDCR TOPCON MODULE',                              quantity: '17',  unitCost: '10620', gstPercent: '5'  },
      { category: 'inverters',          itemName: '10kW String Inverter',                       specification: 'SOLAR GRID TIED STRING INVERTER-10KW 3PH MAKE:DEYE/GROWATT/SUNWAYS', quantity: '1', unitCost: '48000', gstPercent: '5' },
      { category: 'ac-db',              itemName: '10KW 3PH ACDB',                              specification: '10KW 3PH ACDB PREMIUM HAVELLS',                            quantity: '1',   unitCost: '4500',  gstPercent: '18' },
      { category: 'dc-db',              itemName: '10KW 2IN 2OUT DCDB',                         specification: '10KW 2IN 2OUT DCDB PREMIUM HAVELLS',                       quantity: '1',   unitCost: '6500',  gstPercent: '18' },
      { category: 'dc-cable',           itemName: '4SQMM DC Cable Polycab',                     specification: '4SQMM DC CABLE POLYCAB',                                   quantity: '200', unitCost: '41',    gstPercent: '18' },
      { category: 'ac-cable',           itemName: '16SQMM AC AL Cable Havells',                 specification: '16SQMM AC AL CABLE HAVELLS',                               quantity: '60',  unitCost: '106',   gstPercent: '18' },
      { category: 'earthing',           itemName: 'MC4 Connectors',                             specification: 'MC4 CONNECTORS SIBASS',                                    quantity: '15',  unitCost: '35',    gstPercent: '18' },
      { category: 'earthing',           itemName: 'Bare Copper 10SWG',                          specification: 'BARE COPPER 10SWG',                                        quantity: '120', unitCost: '110',   gstPercent: '18' },
      { category: 'earthing',           itemName: 'Copper Bonded Rod 4ft',                      specification: 'COPPER BONDED ROD 4FT EXCEL',                              quantity: '3',   unitCost: '310',   gstPercent: '18' },
      { category: 'earthing',           itemName: 'Earth Chamber',                              specification: 'EARTH CHAMBER EXCEL',                                     quantity: '3',   unitCost: '300',   gstPercent: '18' },
      { category: 'earthing',           itemName: 'Earth Compound 10 KG',                       specification: 'EARTH COMPOUND 10 KG EXCEL',                               quantity: '1',   unitCost: '200',   gstPercent: '18' },
      { category: 'earthing',           itemName: 'SS Terminal Strip / Earth Bench 4 Pole',     specification: 'SS TERMINAL STRIP/EARTH BENCH 4POLE EXCEL',                quantity: '1',   unitCost: '200',   gstPercent: '18' },
      { category: 'earthing',           itemName: 'PVC Channel 45*45 Cable Tray',               specification: 'PVC CHANNEL 45*45 CABLE TRAY',                             quantity: '3',   unitCost: '100',   gstPercent: '18' },
      { category: 'earthing',           itemName: 'Lightning Arrestor Single Spike',            specification: 'LIGHTNING ARRESTER SINGLE SPIKE EXCEL',                    quantity: '1',   unitCost: '650',   gstPercent: '18' },
      { category: 'meter',              itemName: 'Meter Box 3PH',                              specification: 'METER BOX 3PH',                                            quantity: '1',   unitCost: '1000',  gstPercent: '18' },
      { category: 'meter',              itemName: 'AC Isolator 40A 4P',                         specification: 'AC ISOLATOR 40A 4P HAVELLS',                               quantity: '1',   unitCost: '750',   gstPercent: '18' },
      { category: 'meter',              itemName: '3PH Unidirectional Meter',                   specification: '3PH UNIDIRECTION METER GENUS/VISIONTEK',                   quantity: '1',   unitCost: '6000',  gstPercent: '18' },
      { category: 'mounting-structure', itemName: '25MM ISI Light PVC Pipe Ivory',              specification: '25MM ISI LIGHT PVC PIPE IVORY',                            quantity: '30',  unitCost: '70',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: '25MM Bend Ivory',                            specification: '25MM BEND IVORY',                                          quantity: '30',  unitCost: '8',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: '25MM Tee Ivory',                             specification: '25MM TEE IVORY',                                           quantity: '10',  unitCost: '8',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: '25MM Elbow Ivory',                           specification: '25MM ELBOW IVORY',                                         quantity: '30',  unitCost: '8',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: '25MM Coupling Ivory',                        specification: '25MM COUPLING IVORY',                                      quantity: '10',  unitCost: '8',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: '25MM Flexible Hose Ivory',                   specification: '25MM FLEXIBLE HOSE IVORY',                                 quantity: '3',   unitCost: '12',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: '25MM SS Clamp',                              specification: '25MM SS CLAMP',                                            quantity: '200', unitCost: '5',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: '6MM Plastic Sleeve',                         specification: '6MM PLASTIC SLEEVE',                                       quantity: '5',   unitCost: '7',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Fisher 6MM',                                 specification: 'FISHER 6MM',                                               quantity: '300', unitCost: '1',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Self Taping Screw 6*38 SS',                  specification: 'SELF TAPING SCREW 6*38 SS(1.5")',                          quantity: '100', unitCost: '1.5',   gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Self Taping Screw 6*25 SS',                  specification: 'SELF TAPING SCREW 6*25 SS(1")',                            quantity: '200', unitCost: '1',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: '35MM Mid Clamp',                             specification: '35MM MID CLAMP',                                           quantity: '20',  unitCost: '20',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: '35MM End Clamp',                             specification: '35MM END CLAMP',                                           quantity: '20',  unitCost: '20',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Insulation Tape Red/Black/Green',            specification: 'INSULATION TAPE RED/BLACK/GREEN',                          quantity: '5',   unitCost: '10',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: '20MM Cycle Screw with Washer',               specification: '20MM CYCLE SCREW WITH WASHER',                             quantity: '10',  unitCost: '1',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: '4-6 SQMM CU Ring Lug',                       specification: '4-6 SQMM CU RING LUG',                                     quantity: '20',  unitCost: '4.8',   gstPercent: '18' },
      { category: 'mounting-structure', itemName: '370*4.6 Cable Tie',                          specification: '370*4.6 CABLE TIE',                                        quantity: '100', unitCost: '2',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Base Plate 4*4',                             specification: 'BASE PLATE 4*4',                                           quantity: '2',   unitCost: '60',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Anchor Bolt 8MM',                            specification: 'ANCHOR BOLT 8MM',                                          quantity: '10',  unitCost: '10',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Cutting Wheel',                              specification: 'CUTTING WHEEL',                                            quantity: '20',  unitCost: '20',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Amcos Epoxy Primer Grey 1 Ltr',              specification: 'AMCOS EPOXY PRIMER GREY 1 LTR',                            quantity: '8',   unitCost: '400',   gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Sheenlac Thinner D13 1 Ltr',                 specification: 'SHEENLAC THINNER D13*1 LTR',                               quantity: '8',   unitCost: '200',   gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'GP Pipes 3*1.5',                             specification: 'GP PIPES 3*1.5',                                           quantity: '10',  unitCost: '1100',  gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'GP Pipes 1.5*1.5',                           specification: 'GP PIPES 1.5*1.5',                                         quantity: '15',  unitCost: '850',   gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'End Cap 2x2',                                specification: 'END CAP-2x2',                                              quantity: '50',  unitCost: '10',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Welding Rod 12 Gauge',                       specification: 'WELDING ROD 12 GUAGE',                                     quantity: '1',   unitCost: '400',   gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Sliding Door 4*4',                           specification: "SLIDING DOOR 4*4'",                                        quantity: '1',   unitCost: '4000',  gstPercent: '18' },
      { category: 'others',             itemName: 'Miscellaneous',                              specification: 'MISCELLANEOUS',                                            quantity: '1',   unitCost: '2000',  gstPercent: '18' },
      { category: 'installation',       itemName: 'Structure Labour',                           specification: 'STRUCTURE LABOUR',                                         quantity: '10',  unitCost: '3500',  gstPercent: '18' },
      { category: 'installation',       itemName: 'Electrical Labour',                          specification: 'ELECTRICAL LABOUR',                                        quantity: '10',  unitCost: '1500',  gstPercent: '18' },
      { category: 'installation',       itemName: 'Transportation',                             specification: 'TRANSPORTATION',                                           quantity: '70',  unitCost: '40',    gstPercent: '18' },
      { category: 'installation',       itemName: 'Unloading',                                  specification: 'UNLOADING',                                                quantity: '1',   unitCost: '800',   gstPercent: '18' },
      { category: 'others',             itemName: 'KSEB Liasoning',                             specification: 'KSEB Liasoning',                                           quantity: '1',   unitCost: '2000',  gstPercent: '18' },
      { category: 'installation',       itemName: 'Travel Expenses',                            specification: 'TRAVEL EXPENSES',                                          quantity: '1',   unitCost: '1500',  gstPercent: '18' },
      { category: 'installation',       itemName: 'Electrical Contractor',                      specification: 'ELECTRICAL CONTRACTOR',                                    quantity: '1',   unitCost: '1000',  gstPercent: '18' },
    ],
  },

  // ── 5. 15KW Non DCR Hybrid ──────────────────────────────────────────────────
  {
    id: 'builtin_15kw_hybrid',
    name: '15KW Non DCR Hybrid',
    description: '15 kW Hybrid Solar System with Battery — Non-DCR, 3-Phase',
    savedAt: '2025-01-01T00:00:00.000Z',
    isBuiltIn: true,
    items: [
      { category: 'pv-modules',         itemName: 'BiFacial Module',                            specification: 'RENEWSYS 615 NDCR BIFACIAL MODULE',                        quantity: '24',  unitCost: '11070', gstPercent: '5'  },
      { category: 'inverters',          itemName: '15kW Hybrid Inverter 3PH',                   specification: 'SOLAR GRID TIED HYBRID INVERTER-15KW 3PH MAKE:DEYE',        quantity: '1',   unitCost: '205000',gstPercent: '5'  },
      { category: 'inverters',          itemName: '100AH Lithium Battery',                      specification: '100AH LITHIUM BATTERY',                                    quantity: '7',   unitCost: '75000', gstPercent: '5'  },
      { category: 'inverters',          itemName: 'MCCB for Hybrid 630A / Busbar',              specification: 'MCCB FOR HYBRID-630A/ BUSBAR',                             quantity: '1',   unitCost: '25000', gstPercent: '18' },
      { category: 'ac-db',              itemName: '15KW 3PH ACDB Hybrid with COS',              specification: '15KW 3PH ACDB HYBRID WITH COS PREMIUM HAVELLS',            quantity: '1',   unitCost: '10000', gstPercent: '18' },
      { category: 'dc-db',              itemName: '15KW 3IN 3OUT DCDB',                         specification: '15KW 3IN 3OUT DCDB PREMIUM HAVELLS',                       quantity: '1',   unitCost: '11000', gstPercent: '18' },
      { category: 'dc-cable',           itemName: '4SQMM DC Cable Polycab',                     specification: '4SQMM DC CABLE POLYCAB',                                   quantity: '250', unitCost: '50',    gstPercent: '18' },
      { category: 'ac-cable',           itemName: '4Core 35SQMM AC AL Cable Polycab',           specification: '4CORE 35SQMM AC AL CABLE POLYCAB',                         quantity: '900', unitCost: '260',   gstPercent: '18' },
      { category: 'earthing',           itemName: '35SQMM CU Wire',                             specification: '35SQMM CU WIRE',                                           quantity: '60',  unitCost: '500',   gstPercent: '18' },
      { category: 'earthing',           itemName: 'MC4 Connectors',                             specification: 'MC4 CONNECTORS SIBASS',                                    quantity: '20',  unitCost: '35',    gstPercent: '18' },
      { category: 'earthing',           itemName: 'Bare Copper 10SWG',                          specification: 'BARE COPPER 10SWG',                                        quantity: '150', unitCost: '110',   gstPercent: '18' },
      { category: 'earthing',           itemName: 'Copper Bonded Rod 4ft',                      specification: 'COPPER BONDED ROD 4FT EXCEL',                              quantity: '3',   unitCost: '330',   gstPercent: '18' },
      { category: 'earthing',           itemName: 'Earth Chamber',                              specification: 'EARTH CHAMBER EXCEL',                                     quantity: '3',   unitCost: '350',   gstPercent: '18' },
      { category: 'earthing',           itemName: 'Earth Compound 10 KG',                       specification: 'EARTH COMPOUND 10 KG EXCEL',                               quantity: '3',   unitCost: '280',   gstPercent: '18' },
      { category: 'earthing',           itemName: 'SS Terminal Strip / Earth Bench 4 Pole',     specification: 'SS TERMINAL STRIP/EARTH BENCH 4POLE EXCEL',                quantity: '2',   unitCost: '200',   gstPercent: '18' },
      { category: 'earthing',           itemName: 'PVC Channel 45*45 Cable Tray',               specification: 'PVC CHANNEL 45*45 CABLE TRAY',                             quantity: '3',   unitCost: '100',   gstPercent: '18' },
      { category: 'earthing',           itemName: 'Lightning Arrestor Multi Spike',             specification: 'LIGHTNING ARRESTER MULTI SPIKE EXCEL',                     quantity: '3',   unitCost: '1100',  gstPercent: '18' },
      { category: 'meter',              itemName: 'Meter Box 3PH',                              specification: 'METER BOX 3PH',                                            quantity: '3',   unitCost: '1500',  gstPercent: '18' },
      { category: 'meter',              itemName: 'AC Isolator 40A 4P',                         specification: 'AC ISOLATOR 40A 4P HAVELLS',                               quantity: '3',   unitCost: '750',   gstPercent: '18' },
      { category: 'meter',              itemName: '3PH Unidirectional Meter',                   specification: '3PH UNIDIRECTION METER GENUS/VISIONTEK',                   quantity: '2',   unitCost: '6700',  gstPercent: '18' },
      { category: 'meter',              itemName: '3PH Bidirectional Meter',                    specification: '3PH BIDIRECTION METER GENUS/VISIONTEK',                    quantity: '1',   unitCost: '10000', gstPercent: '18' },
      { category: 'mounting-structure', itemName: '25MM ISI Light PVC Pipe Ivory',              specification: '25MM ISI LIGHT PVC PIPE IVORY',                            quantity: '40',  unitCost: '60',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: '25MM Bend Ivory',                            specification: '25MM BEND IVORY',                                          quantity: '50',  unitCost: '10',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: '25MM Tee Ivory',                             specification: '25MM TEE IVORY',                                           quantity: '30',  unitCost: '10',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: '25MM Elbow Ivory',                           specification: '25MM ELBOW IVORY',                                         quantity: '50',  unitCost: '10',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: '25MM Coupling Ivory',                        specification: '25MM COUPLING IVORY',                                      quantity: '10',  unitCost: '10',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: '25MM Flexible Hose Ivory',                   specification: '25MM FLEXIBLE HOSE IVORY',                                 quantity: '3',   unitCost: '12',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: '25MM SS Clamp',                              specification: '25MM SS CLAMP',                                            quantity: '300', unitCost: '5',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: '6MM Plastic Sleeve',                         specification: '6MM PLASTIC SLEEVE',                                       quantity: '5',   unitCost: '7',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Fisher 6MM',                                 specification: 'FISHER 6MM',                                               quantity: '400', unitCost: '1',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Self Taping Screw 6*38 SS',                  specification: 'SELF TAPING SCREW 6*38 SS(1.5")',                          quantity: '300', unitCost: '1.5',   gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Self Taping Screw 6*25 SS',                  specification: 'SELF TAPING SCREW 6*25 SS(1")',                            quantity: '150', unitCost: '1',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: '35MM Mid Clamp',                             specification: '35MM MID CLAMP',                                           quantity: '15',  unitCost: '20',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: '35MM End Clamp',                             specification: '35MM END CLAMP',                                           quantity: '40',  unitCost: '20',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Insulation Tape Red/Black/Green',            specification: 'INSULATION TAPE RED/BLACK/GREEN',                          quantity: '8',   unitCost: '10',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: '20MM Cycle Screw with Washer',               specification: '20MM CYCLE SCREW WITH WASHER',                             quantity: '10',  unitCost: '1',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: '4-6 SQMM CU Ring Lug',                       specification: '4-6 SQMM CU RING LUG',                                     quantity: '20',  unitCost: '4.8',   gstPercent: '18' },
      { category: 'mounting-structure', itemName: '370*4.6 Cable Tie',                          specification: '370*4.6 CABLE TIE',                                        quantity: '100', unitCost: '2',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Base Plate 4*4',                             specification: 'BASE PLATE 4*4',                                           quantity: '3',   unitCost: '60',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Anchor Bolt 8MM',                            specification: 'ANCHOR BOLT 8MM',                                          quantity: '10',  unitCost: '10',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Cutting Wheel',                              specification: 'CUTTING WHEEL',                                            quantity: '20',  unitCost: '20',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Amcos Epoxy Primer Grey 1 Ltr',              specification: 'AMCOS EPOXY PRIMER GREY 1 LTR',                            quantity: '4',   unitCost: '400',   gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Sheenlac Thinner D13 1 Ltr',                 specification: 'SHEENLAC THINNER D13*1 LTR',                               quantity: '4',   unitCost: '200',   gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'GP Pipes 3*1.5',                             specification: 'GP PIPES 3*1.5',                                           quantity: '12',  unitCost: '1250',  gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'GP Pipes 1.5*1.5',                           specification: 'GP PIPES 1.5*1.5',                                         quantity: '10',  unitCost: '850',   gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'GP Pipes 2*1',                               specification: 'GP PIPES 2*1',                                             quantity: '25',  unitCost: '850',   gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'End Cap 3*1.5',                              specification: 'END CAP-3*1.5',                                            quantity: '100', unitCost: '10',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Welding Rod 12 Gauge',                       specification: 'WELDING ROD 12 GUAGE',                                     quantity: '1',   unitCost: '400',   gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Sliding Door 4*4',                           specification: "SLIDING DOOR 4*4'",                                        quantity: '1',   unitCost: '4000',  gstPercent: '18' },
      { category: 'others',             itemName: 'Miscellaneous',                              specification: 'MISCELLANEOUS',                                            quantity: '1',   unitCost: '2500',  gstPercent: '18' },
      { category: 'installation',       itemName: 'Structure Labour',                           specification: 'STRUCTURE LABOUR',                                         quantity: '15',  unitCost: '4000',  gstPercent: '18' },
      { category: 'installation',       itemName: 'Electrical Labour',                          specification: 'ELECTRICAL LABOUR',                                        quantity: '15',  unitCost: '3000',  gstPercent: '18' },
      { category: 'installation',       itemName: 'Transportation',                             specification: 'TRANSPORTATION',                                           quantity: '200', unitCost: '40',    gstPercent: '18' },
      { category: 'installation',       itemName: 'Unloading',                                  specification: 'UNLOADING',                                                quantity: '1',   unitCost: '3500',  gstPercent: '18' },
      { category: 'others',             itemName: 'KSEB Liasoning',                             specification: 'KSEB Liasoning',                                           quantity: '1',   unitCost: '2000',  gstPercent: '18' },
      { category: 'installation',       itemName: 'Travel Expenses',                            specification: 'TRAVEL EXPENSES',                                          quantity: '1',   unitCost: '5000',  gstPercent: '18' },
      { category: 'installation',       itemName: 'Electrical Contractor',                      specification: 'ELECTRICAL CONTRACTOR',                                    quantity: '1',   unitCost: '15000', gstPercent: '18' },
    ],
  },

  // ── 6. 25KW Non DCR ─────────────────────────────────────────────────────────
  {
    id: 'builtin_25kw_nondcr',
    name: '25KW Non DCR',
    description: '25 kW On-Grid Commercial — Non-DCR, 3-Phase',
    savedAt: '2025-01-01T00:00:00.000Z',
    isBuiltIn: true,
    items: [
      { category: 'pv-modules',         itemName: 'TopCon Module',                              specification: 'NDCR WAAREE/RENEWSYS 580-635 WP TOPCON MODULE',             quantity: '40',  unitCost: '10795', gstPercent: '5'  },
      { category: 'inverters',          itemName: '25kW String Inverter 3PH',                   specification: 'SOLAR GRID TIED STRING INVERTER-25KW 3PH MAKE: SUNWATT/DEYE/FOXESS', quantity: '1', unitCost: '82000', gstPercent: '5' },
      { category: 'ac-db',              itemName: '25KW 3PH ACDB',                              specification: '25KW 1PH ACDB PREMIUM HAVELLS',                            quantity: '1',   unitCost: '7000',  gstPercent: '18' },
      { category: 'dc-db',              itemName: '25KW 4IN 4OUT DCDB',                         specification: '25KW 4IN 4OUT DCDB PREMIUM HAVELLS',                       quantity: '1',   unitCost: '13000', gstPercent: '18' },
      { category: 'dc-cable',           itemName: '4SQMM DC Cable Polycab',                     specification: '4SQMM DC CABLE POLYCAB',                                   quantity: '300', unitCost: '41',    gstPercent: '18' },
      { category: 'ac-cable',           itemName: '4C 25SQMM AC AL Armoured Cable',             specification: '4C 25SQMM AL ARMOURED CABLE',                              quantity: '50',  unitCost: '220',   gstPercent: '18' },
      { category: 'earthing',           itemName: 'MC4 Connectors',                             specification: 'MC4 CONNECTORS',                                           quantity: '20',  unitCost: '35',    gstPercent: '18' },
      { category: 'earthing',           itemName: 'Bare Copper 10SWG',                          specification: 'BARE COPPER 10SWG',                                        quantity: '150', unitCost: '80',    gstPercent: '18' },
      { category: 'earthing',           itemName: 'Copper Bonded Rod 4ft',                      specification: 'COPPER BONDED ROD 4FT EXCEL',                              quantity: '3',   unitCost: '310',   gstPercent: '18' },
      { category: 'earthing',           itemName: 'Earth Chamber',                              specification: 'EARTH CHAMBER EXCEL',                                     quantity: '3',   unitCost: '300',   gstPercent: '18' },
      { category: 'earthing',           itemName: 'Earth Compound 10 KG',                       specification: 'EARTH COMPOUND 10 KG EXCEL',                               quantity: '3',   unitCost: '200',   gstPercent: '18' },
      { category: 'earthing',           itemName: 'SS Terminal Strip / Earth Bench 4 Pole',     specification: 'SS TERMINAL STRIP/EARTH BENCH 4POLE EXCEL',                quantity: '2',   unitCost: '200',   gstPercent: '18' },
      { category: 'earthing',           itemName: 'PVC Channel 45*45 Cable Tray',               specification: 'PVC CHANNEL 45*45 CABLE TRAY',                             quantity: '3',   unitCost: '100',   gstPercent: '18' },
      { category: 'earthing',           itemName: 'Lightning Arrestor Multi Spike',             specification: 'LIGHTNING ARRESTER MULTI SPIKE EXCEL',                     quantity: '2',   unitCost: '1200',  gstPercent: '18' },
      { category: 'meter',              itemName: 'Meter Box 3PH',                              specification: 'METER BOX 3PH',                                            quantity: '1',   unitCost: '1300',  gstPercent: '18' },
      { category: 'meter',              itemName: 'AC Isolator 63A 3P',                         specification: 'AC ISOLATOR 63A 3P HAVELLS',                               quantity: '1',   unitCost: '800',   gstPercent: '18' },
      { category: 'meter',              itemName: '3PH Unidirectional Meter',                   specification: '3PH UNIDIRECTION METER GENUS/VISIONTEK',                   quantity: '1',   unitCost: '6000',  gstPercent: '18' },
      { category: 'mounting-structure', itemName: '25MM ISI Light PVC Pipe Ivory',              specification: '25MM ISI LIGHT PVC PIPE IVORY',                            quantity: '40',  unitCost: '70',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: '25MM Bend Ivory',                            specification: '25MM BEND IVORY',                                          quantity: '50',  unitCost: '7',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: '25MM Tee Ivory',                             specification: '25MM TEE IVORY',                                           quantity: '10',  unitCost: '7',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: '25MM Elbow Ivory',                           specification: '25MM ELBOW IVORY',                                         quantity: '50',  unitCost: '7',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: '25MM Coupling Ivory',                        specification: '25MM COUPLING IVORY',                                      quantity: '10',  unitCost: '7',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: '25MM Flexible Hose Ivory',                   specification: '25MM FLEXIBLE HOSE IVORY',                                 quantity: '5',   unitCost: '12',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: '25MM SS Clamp',                              specification: '25MM SS CLAMP',                                            quantity: '300', unitCost: '4',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: '6MM Plastic Sleeve',                         specification: '6MM PLASTIC SLEEVE',                                       quantity: '3',   unitCost: '7',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Fisher 6MM',                                 specification: 'FISHER 6MM',                                               quantity: '400', unitCost: '1',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Self Taping Screw 6*38 SS',                  specification: 'SELF TAPING SCREW 6*38 SS(1.5")',                          quantity: '150', unitCost: '1.5',   gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Self Taping Screw 6*25 SS',                  specification: 'SELF TAPING SCREW 6*25 SS(1")',                            quantity: '300', unitCost: '1',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: '35MM Mid Clamp',                             specification: '35MM MID CLAMP',                                           quantity: '50',  unitCost: '20',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: '35MM End Clamp',                             specification: '35MM END CLAMP',                                           quantity: '30',  unitCost: '20',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Insulation Tape Red/Black/Green',            specification: 'INSULATION TAPE RED/BLACK/GREEN',                          quantity: '5',   unitCost: '10',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: '20MM Cycle Screw with Washer',               specification: '20MM CYCLE SCREW WITH WASHER',                             quantity: '10',  unitCost: '1',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: '4-6 SQMM CU Ring Lug',                       specification: '4-6 SQMM CU RING LUG',                                     quantity: '20',  unitCost: '4.8',   gstPercent: '18' },
      { category: 'mounting-structure', itemName: '370*4.6 Cable Tie',                          specification: '370*4.6 CABLE TIE',                                        quantity: '100', unitCost: '2',     gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Base Plate 4*4',                             specification: 'BASE PLATE 4*4',                                           quantity: '2',   unitCost: '60',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Anchor Bolt 8MM',                            specification: 'ANCHOR BOLT 8MM',                                          quantity: '10',  unitCost: '10',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Cutting Wheel',                              specification: 'CUTTING WHEEL',                                            quantity: '30',  unitCost: '20',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Amcos Epoxy Primer Grey 1 Ltr',              specification: 'AMCOS EPOXY PRIMER GREY 1 LTR',                            quantity: '8',   unitCost: '400',   gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Sheenlac Thinner D13 1 Ltr',                 specification: 'SHEENLAC THINNER D13*1 LTR',                               quantity: '8',   unitCost: '200',   gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'GP Pipes 3*1.5',                             specification: 'GP PIPES 3*1.5',                                           quantity: '20',  unitCost: '1100',  gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'GP Pipes 1.5*1.5',                           specification: 'GP PIPES 1.5*1.5',                                         quantity: '50',  unitCost: '850',   gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'End Cap 2x2',                                specification: 'END CAP-2x2',                                              quantity: '100', unitCost: '10',    gstPercent: '18' },
      { category: 'mounting-structure', itemName: 'Welding Rod 12 Gauge',                       specification: 'WELDING ROD 12 GUAGE',                                     quantity: '2',   unitCost: '400',   gstPercent: '18' },
      { category: 'others',             itemName: 'Miscellaneous',                              specification: 'MISCELLANEOUS',                                            quantity: '1',   unitCost: '10000', gstPercent: '18' },
      { category: 'installation',       itemName: 'Structure Labour',                           specification: 'STRUCTURE LABOUR',                                         quantity: '25',  unitCost: '4000',  gstPercent: '18' },
      { category: 'installation',       itemName: 'Electrical Labour',                          specification: 'ELECTRICAL LABOUR',                                        quantity: '25',  unitCost: '2000',  gstPercent: '18' },
      { category: 'installation',       itemName: 'Transportation',                             specification: 'TRANSPORTATION',                                           quantity: '70',  unitCost: '40',    gstPercent: '18' },
      { category: 'installation',       itemName: 'Unloading',                                  specification: 'UNLOADING',                                                quantity: '1',   unitCost: '1500',  gstPercent: '18' },
      { category: 'others',             itemName: 'KSEB Liasoning',                             specification: 'KSEB Liasoning',                                           quantity: '1',   unitCost: '4000',  gstPercent: '18' },
      { category: 'installation',       itemName: 'Travel Expenses',                            specification: 'TRAVEL EXPENSES',                                          quantity: '1',   unitCost: '3000',  gstPercent: '18' },
      { category: 'installation',       itemName: 'Electrical Contractor',                      specification: 'ELECTRICAL CONTRACTOR',                                    quantity: '1',   unitCost: '1000',  gstPercent: '18' },
    ],
  },
];

export function loadTemplates(): CostingTemplate[] {
  // Initial in-memory templates: built-ins only.
  // User-saved templates are loaded from the backend via fetchCostingTemplates.
  return [...BUILT_IN_TEMPLATES];
}

export function templateTotal(items: LineItem[]): number {
  return items.reduce((s, r) => s + toNum(r.quantity) * toNum(r.unitCost), 0);
}
