import { prisma } from '../lib/prisma';

// ─────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────

export interface BomRow {
  id?: number;             // present when persisted
  proposalId: number;
  itemName: string;
  specification: string;
  quantity: number;
  brand: string;
  warranty: string;
  isAutoGenerated: boolean;
}

export interface SaveBomInput {
  proposalId: number;
  rows: Omit<BomRow, 'id' | 'proposalId' | 'isAutoGenerated'>[];
}

// ─────────────────────────────────────────────
// Default brand / warranty lookup by category
// These are sensible solar-industry defaults.
// Users can override them in the UI.
// ─────────────────────────────────────────────

const CATEGORY_DEFAULTS: Record<
  string,
  { brand: string; warranty: string; specification: string }
> = {
  module:    { brand: 'Waaree / Adani',   warranty: '25 years',  specification: 'Mono PERC, 540W' },
  inverter:  { brand: 'Solis / Growatt',  warranty: '5 years',   specification: 'String Inverter, IP65' },
  structure: { brand: 'Mounting Systems', warranty: '10 years',  specification: 'Hot-dip GI, 2mm' },
  cable:     { brand: 'Polycab / Havells', warranty: '10 years', specification: 'DC 4mm², UV resistant' },
  labour:    { brand: 'In-house',          warranty: '1 year',   specification: 'Certified installation team' },
  misc:      { brand: '-',                 warranty: '-',         specification: '-' },
};

// ─────────────────────────────────────────────
// Grouping logic
//
// Strategy:
//   1. Normalise item names (lowercase, trim)
//   2. Group by (category + normalised name)
//   3. Sum quantities within each group
//   4. Apply category defaults for brand/warranty/spec
//      (overridable by the user in the UI)
// ─────────────────────────────────────────────

function normalise(name: string): string {
  return name.toLowerCase().trim().replace(/\s+/g, ' ');
}

export function generateBomFromCosting(
  proposalId: number,
  costingItems: Array<{
    category: string;
    itemName: string;
    quantity: number;
  }>
): BomRow[] {
  // Group by category + normalised item name
  const grouped = new Map<string, { category: string; itemName: string; quantity: number }>();

  for (const item of costingItems) {
    const key = `${item.category}::${normalise(item.itemName)}`;
    const existing = grouped.get(key);
    if (existing) {
      existing.quantity = Math.round((existing.quantity + item.quantity) * 1000) / 1000;
    } else {
      grouped.set(key, {
        category: item.category,
        itemName: item.itemName.trim(),
        quantity: item.quantity,
      });
    }
  }

  // Map each group to a BomRow with defaults
  const rows: BomRow[] = [];
  for (const { category, itemName, quantity } of grouped.values()) {
    const defaults = CATEGORY_DEFAULTS[category] ?? CATEGORY_DEFAULTS.misc;
    rows.push({
      proposalId,
      itemName,
      specification: defaults.specification,
      quantity,
      brand: defaults.brand,
      warranty: defaults.warranty,
      isAutoGenerated: true,
    });
  }

  return rows;
}

// ─────────────────────────────────────────────
// Persistence
// ─────────────────────────────────────────────

/**
 * Replace all BOM rows for a proposal (upsert pattern).
 * Called when the user saves manual overrides from the UI.
 */
export async function saveBom(input: SaveBomInput): Promise<BomRow[]> {
  const { proposalId, rows } = input;

  // Verify proposal exists
  const proposal = await prisma.proposal.findUnique({
    where: { id: proposalId },
    select: { id: true },
  });
  if (!proposal) throw new Error(`Proposal ${proposalId} not found`);

  // Delete existing BOM rows for this proposal, then re-insert
  await prisma.bOMItem.deleteMany({ where: { proposalId } });

  const created = await prisma.bOMItem.createMany({
    data: rows.map((r) => ({
      proposalId,
      itemName: r.itemName,
      specification: r.specification,
      quantity: r.quantity,
      brand: r.brand,
      warranty: r.warranty,
    })),
  });

  // Return the freshly saved rows
  const saved = await prisma.bOMItem.findMany({
    where: { proposalId },
    orderBy: { id: 'asc' },
  });

  return saved.map((r) => ({ ...r, isAutoGenerated: false }));
}

/**
 * Fetch the BOM for a proposal.
 *
 * Behaviour:
 *   - If saved BOM rows exist → return them (manual overrides preserved)
 *   - If no saved rows → auto-generate from costing items (non-destructive)
 */
export async function getBom(proposalId: number): Promise<{
  source: 'saved' | 'generated';
  rows: BomRow[];
}> {
  // Check for saved rows first
  const saved = await prisma.bOMItem.findMany({
    where: { proposalId },
    orderBy: { id: 'asc' },
  });

  if (saved.length > 0) {
    return {
      source: 'saved',
      rows: saved.map((r) => ({ ...r, isAutoGenerated: false })),
    };
  }

  // No saved rows — auto-generate from costing items
  const costingItems = await prisma.costingItem.findMany({
    where: { proposalId },
    orderBy: { id: 'asc' },
  });

  if (costingItems.length === 0) {
    return { source: 'generated', rows: [] };
  }

  const rows = generateBomFromCosting(proposalId, costingItems);
  return { source: 'generated', rows };
}
