import { useEffect, useState } from 'react';
import { useForm, useFieldArray, useWatch } from 'react-hook-form';

// ─────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────

interface BomRow {
  itemName: string;
  specification: string;
  quantity: string;
  brand: string;
  warranty: string;
  isAutoGenerated: boolean;
}

interface FormValues {
  rows: BomRow[];
}

interface ApiRow {
  id?: number;
  proposalId: number;
  itemName: string;
  specification: string;
  quantity: number;
  brand: string;
  warranty: string;
  isAutoGenerated: boolean;
}

interface ApiResponse {
  proposalId: number;
  source: 'saved' | 'generated';
  count: number;
  data: ApiRow[];
}

// ─────────────────────────────────────────────
// Constants — proposal id is hardcoded to 2
// (the one we created in the live test).
// In a real app this comes from a route param.
// ─────────────────────────────────────────────

const PROPOSAL_ID = 2;

// ─────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────

function apiRowToFormRow(r: ApiRow): BomRow {
  return {
    itemName: r.itemName,
    specification: r.specification,
    quantity: String(r.quantity),
    brand: r.brand,
    warranty: r.warranty,
    isAutoGenerated: r.isAutoGenerated,
  };
}

const EMPTY_ROW: BomRow = {
  itemName: '',
  specification: '',
  quantity: '1',
  brand: '',
  warranty: '',
  isAutoGenerated: false,
};

// ─────────────────────────────────────────────
// BOM row component
// ─────────────────────────────────────────────

function BomRowInput({
  index,
  control,
  register,
  onRemove,
}: {
  index: number;
  control: ReturnType<typeof useForm<FormValues>>['control'];
  register: ReturnType<typeof useForm<FormValues>>['register'];
  onRemove: () => void;
}) {
  const isAuto = useWatch({ control, name: `rows.${index}.isAutoGenerated` });

  return (
    <tr className="group border-b border-gray-800/60 hover:bg-gray-800/20 transition-colors">
      {/* Auto badge */}
      <td className="px-3 py-2 w-16 text-center">
        {isAuto ? (
          <span className="text-[10px] px-1.5 py-0.5 rounded border bg-indigo-950/60 text-indigo-300 border-indigo-800/50 whitespace-nowrap">
            auto
          </span>
        ) : (
          <span className="text-[10px] px-1.5 py-0.5 rounded border bg-amber-950/60 text-amber-300 border-amber-800/50 whitespace-nowrap">
            manual
          </span>
        )}
      </td>

      {/* Item name */}
      <td className="px-3 py-2">
        <input
          {...register(`rows.${index}.itemName`)}
          placeholder="Item name"
          className="w-full bg-transparent text-sm text-white placeholder-gray-600 focus:outline-none"
        />
      </td>

      {/* Specification */}
      <td className="px-3 py-2">
        <input
          {...register(`rows.${index}.specification`)}
          placeholder="e.g. Mono PERC, 540W"
          className="w-full bg-transparent text-sm text-gray-300 placeholder-gray-600 focus:outline-none"
        />
      </td>

      {/* Qty */}
      <td className="px-3 py-2 w-20">
        <input
          {...register(`rows.${index}.quantity`)}
          type="number"
          min="0"
          step="any"
          placeholder="0"
          className="w-full bg-transparent text-sm text-right text-white placeholder-gray-600 focus:outline-none tabular-nums"
        />
      </td>

      {/* Brand */}
      <td className="px-3 py-2 w-36">
        <input
          {...register(`rows.${index}.brand`)}
          placeholder="Brand"
          className="w-full bg-transparent text-sm text-gray-300 placeholder-gray-600 focus:outline-none"
        />
      </td>

      {/* Warranty */}
      <td className="px-3 py-2 w-28">
        <input
          {...register(`rows.${index}.warranty`)}
          placeholder="e.g. 25 years"
          className="w-full bg-transparent text-sm text-gray-300 placeholder-gray-600 focus:outline-none"
        />
      </td>

      {/* Remove */}
      <td className="px-2 py-2 w-8 text-center">
        <button
          type="button"
          onClick={onRemove}
          title="Remove row"
          className="opacity-0 group-hover:opacity-100 transition-opacity text-gray-600 hover:text-red-400 text-lg leading-none"
        >
          ×
        </button>
      </td>
    </tr>
  );
}

// ─────────────────────────────────────────────
// Main page
// ─────────────────────────────────────────────

export default function BOMSheet() {
  const [loading, setLoading] = useState(true);
  const [source, setSource] = useState<'saved' | 'generated' | null>(null);
  const [fetchError, setFetchError] = useState<string | null>(null);
  const [saveStatus, setSaveStatus] = useState<'idle' | 'saving' | 'saved' | 'error'>('idle');

  const { control, register, handleSubmit, reset } = useForm<FormValues>({
    defaultValues: { rows: [] },
  });

  const { fields, append, remove } = useFieldArray({ control, name: 'rows' });

  // ── Fetch BOM on mount ──────────────────────
  useEffect(() => {
    setLoading(true);
    fetch(`/api/proposal/${PROPOSAL_ID}/bom`)
      .then((r) => {
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        return r.json() as Promise<ApiResponse>;
      })
      .then((res) => {
        setSource(res.source);
        reset({ rows: res.data.map(apiRowToFormRow) });
        setLoading(false);
      })
      .catch((e: Error) => {
        setFetchError(e.message);
        setLoading(false);
      });
  }, [reset]);

  // ── Save overrides ──────────────────────────
  const onSubmit = async (data: FormValues) => {
    setSaveStatus('saving');
    try {
      const payload = {
        rows: data.rows.map((r) => ({
          itemName: r.itemName,
          specification: r.specification,
          quantity: parseFloat(r.quantity) || 0,
          brand: r.brand,
          warranty: r.warranty,
        })),
      };

      const res = await fetch(`/api/proposal/${PROPOSAL_ID}/bom`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
      });

      if (!res.ok) {
        const err = (await res.json()) as { error: string };
        throw new Error(err.error);
      }

      const saved = (await res.json()) as ApiResponse;
      setSource('saved');
      reset({ rows: saved.data.map(apiRowToFormRow) });
      setSaveStatus('saved');
      setTimeout(() => setSaveStatus('idle'), 2500);
    } catch (e) {
      setSaveStatus('error');
      setTimeout(() => setSaveStatus('idle'), 3000);
    }
  };

  // ─────────────────────────────────────────────
  // Render
  // ─────────────────────────────────────────────

  return (
    <div>
      {/* Page header — stacks on mobile */}
      <div className="mb-8 flex flex-col sm:flex-row sm:items-start sm:justify-between gap-3">
        <div>
          <h1 className="text-2xl font-bold text-white tracking-tight">Bill of Materials</h1>
          <p className="text-gray-400 text-sm mt-1">
            Auto-generated from costing items. Edit brand, warranty, and specs as needed.
          </p>
        </div>

        {source && (
          <div className="flex items-center gap-3 flex-shrink-0">
            <span
              className={`text-xs px-3 py-1 rounded-full border ${
                source === 'saved'
                  ? 'bg-emerald-950/50 text-emerald-300 border-emerald-800/50'
                  : 'bg-indigo-950/50 text-indigo-300 border-indigo-800/50'
              }`}
            >
              {source === 'saved' ? 'Saved overrides' : 'Auto-generated'}
            </span>
          </div>
        )}
      </div>

      {/* Loading / error states */}
      {loading && (
        <div className="flex items-center gap-3 text-gray-400 text-sm py-12 justify-center">
          <span className="w-4 h-4 border-2 border-gray-600 border-t-indigo-400 rounded-full animate-spin" />
          Generating BOM from costing items…
        </div>
      )}

      {fetchError && (
        <div className="bg-red-950/30 border border-red-800/50 rounded-xl px-5 py-4 text-red-300 text-sm">
          Failed to load BOM: {fetchError}
        </div>
      )}

      {!loading && !fetchError && (
        <form onSubmit={handleSubmit(onSubmit)}>
          {/* Table */}
          <div className="bg-gray-900 border border-gray-800 rounded-xl overflow-x-auto">
            <table className="w-full border-collapse min-w-[800px]">
              <thead>
                <tr className="border-b border-gray-800">
                  <th className="px-3 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wide w-16">
                    Source
                  </th>
                  <th className="px-3 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wide">
                    Item / Description
                  </th>
                  <th className="px-3 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wide">
                    Specification
                  </th>
                  <th className="px-3 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wide w-20">
                    Qty
                  </th>
                  <th className="px-3 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wide w-36">
                    Brand
                  </th>
                  <th className="px-3 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wide w-28">
                    Warranty
                  </th>
                  <th className="w-8" />
                </tr>
              </thead>

              <tbody>
                {fields.length === 0 ? (
                  <tr>
                    <td colSpan={7} className="px-4 py-10 text-center text-gray-500 text-sm">
                      No costing items found. Add items in the Costing Sheet first.
                    </td>
                  </tr>
                ) : (
                  fields.map((field, index) => (
                    <BomRowInput
                      key={field.id}
                      index={index}
                      control={control}
                      register={register}
                      onRemove={() => {
                        remove(index);
                      }}
                    />
                  ))
                )}
              </tbody>

              {fields.length > 0 && (
                <tfoot>
                  <tr className="border-t-2 border-gray-700 bg-gray-900/40">
                    <td colSpan={3} className="px-3 py-3 text-xs text-gray-500 uppercase tracking-wide">
                      Total items
                    </td>
                    <td className="px-3 py-3 text-right text-sm text-white font-semibold tabular-nums">
                      {fields.length}
                    </td>
                    <td colSpan={3} />
                  </tr>
                </tfoot>
              )}
            </table>
          </div>

          {/* Actions — wraps on narrow screens */}
          <div className="mt-4 flex flex-wrap items-center justify-between gap-3">
            <button
              type="button"
              onClick={() => append({ ...EMPTY_ROW })}
              className="flex items-center gap-2 text-sm text-indigo-400 hover:text-indigo-300 transition-colors px-3 py-2 rounded-lg hover:bg-indigo-950/30"
            >
              <span className="text-lg leading-none">+</span>
              Add row
            </button>

            <div className="flex items-center gap-3">
              {/* Save status feedback */}
              {saveStatus === 'saved' && (
                <span className="text-xs text-emerald-400 animate-pulse">Saved</span>
              )}
              {saveStatus === 'error' && (
                <span className="text-xs text-red-400">Save failed</span>
              )}

              <button
                type="submit"
                disabled={saveStatus === 'saving'}
                className="text-sm bg-indigo-600 hover:bg-indigo-500 disabled:opacity-50 text-white px-5 py-2 rounded-lg transition-colors font-medium flex items-center gap-2"
              >
                {saveStatus === 'saving' && (
                  <span className="w-3 h-3 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                )}
                Save BOM
              </button>
            </div>
          </div>
        </form>
      )}

      {/* Info panel */}
      {!loading && !fetchError && (
        <div className="mt-8 bg-gray-900/50 border border-gray-800 rounded-xl p-5">
          <h3 className="text-sm font-medium text-gray-300 mb-3">How BOM generation works</h3>
          <ul className="space-y-2 text-xs text-gray-500">
            <li className="flex items-start gap-2">
              <span className="text-indigo-400 mt-0.5">1.</span>
              Costing items with the same name and category are grouped and their quantities summed.
            </li>
            <li className="flex items-start gap-2">
              <span className="text-indigo-400 mt-0.5">2.</span>
              Default brand, warranty, and specification are filled from solar-industry standards per category.
            </li>
            <li className="flex items-start gap-2">
              <span className="text-indigo-400 mt-0.5">3.</span>
              Edit any field and click <strong className="text-gray-300">Save BOM</strong> — your overrides are persisted and won't be overwritten on the next load.
            </li>
            <li className="flex items-start gap-2">
              <span className="text-indigo-400 mt-0.5">4.</span>
              Add manual rows for items not in the costing sheet (accessories, transport, etc.).
            </li>
          </ul>
        </div>
      )}
    </div>
  );
}
