import { useEffect, useState } from 'react';
import { useForm, useFieldArray, useWatch } from 'react-hook-form';

// ─────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────

interface BomRow {
  itemName: string;
  specification: string;
  quantity: string;
  brand: string;
  warranty: string;
  isAutoGenerated: boolean;
}

interface FormValues {
  rows: BomRow[];
}

interface ApiRow {
  id?: number;
  proposalId: number;
  itemName: string;
  specification: string;
  quantity: number;
  brand: string;
  warranty: string;
  isAutoGenerated: boolean;
}

interface ApiResponse {
  proposalId: number;
  source: 'saved' | 'generated';
  count: number;
  data: ApiRow[];
}

const PROPOSAL_ID = 2;

function apiRowToFormRow(r: ApiRow): BomRow {
  return {
    itemName: r.itemName,
    specification: r.specification,
    quantity: String(r.quantity),
    brand: r.brand,
    warranty: r.warranty,
    isAutoGenerated: r.isAutoGenerated,
  };
}

const EMPTY_ROW: BomRow = {
  itemName: '',
  specification: '',
  quantity: '1',
  brand: '',
  warranty: '',
  isAutoGenerated: false,
};

// ─────────────────────────────────────────────
// BOM row component
// ─────────────────────────────────────────────

function BomRowInput({
  index,
  control,
  register,
  onRemove,
}: {
  index: number;
  control: ReturnType<typeof useForm<FormValues>>['control'];
  register: ReturnType<typeof useForm<FormValues>>['register'];
  onRemove: () => void;
}) {
  const isAuto = useWatch({ control, name: `rows.${index}.isAutoGenerated` });

  return (
    <tr className="group border-b border-primary-100/60 hover:bg-primary-50/40 transition-colors">
      {/* Auto badge */}
      <td className="px-3 py-2 w-16 text-center">
        {isAuto ? (
          <span className="text-[10px] px-1.5 py-0.5 rounded border bg-primary-50 text-primary-600 border-primary-200 whitespace-nowrap font-medium">
            auto
          </span>
        ) : (
          <span className="text-[10px] px-1.5 py-0.5 rounded border bg-yellow-50 text-yellow-700 border-yellow-200 whitespace-nowrap font-medium">
            manual
          </span>
        )}
      </td>

      {/* Item name */}
      <td className="px-3 py-2">
        <input
          {...register(`rows.${index}.itemName`)}
          placeholder="Item name"
          className="w-full bg-transparent text-sm text-secondary-800 placeholder-secondary-400 focus:outline-none"
        />
      </td>

      {/* Specification */}
      <td className="px-3 py-2">
        <input
          {...register(`rows.${index}.specification`)}
          placeholder="e.g. Mono PERC, 540W"
          className="w-full bg-transparent text-sm text-secondary-600 placeholder-secondary-400 focus:outline-none"
        />
      </td>

      {/* Qty */}
      <td className="px-3 py-2 w-20">
        <input
          {...register(`rows.${index}.quantity`)}
          type="number"
          min="0"
          step="any"
          placeholder="0"
          className="w-full bg-transparent text-sm text-right text-secondary-800 placeholder-secondary-400 focus:outline-none tabular-nums"
        />
      </td>

      {/* Brand */}
      <td className="px-3 py-2 w-36">
        <input
          {...register(`rows.${index}.brand`)}
          placeholder="Brand"
          className="w-full bg-transparent text-sm text-secondary-600 placeholder-secondary-400 focus:outline-none"
        />
      </td>

      {/* Warranty */}
      <td className="px-3 py-2 w-28">
        <input
          {...register(`rows.${index}.warranty`)}
          placeholder="e.g. 25 years"
          className="w-full bg-transparent text-sm text-secondary-600 placeholder-secondary-400 focus:outline-none"
        />
      </td>

      {/* Remove */}
      <td className="px-2 py-2 w-8 text-center">
        <button
          type="button"
          onClick={onRemove}
          title="Remove row"
          className="opacity-0 group-hover:opacity-100 transition-opacity text-secondary-400 hover:text-red-500 text-lg leading-none"
        >
          ×
        </button>
      </td>
    </tr>
  );
}

// ─────────────────────────────────────────────
// Main page
// ─────────────────────────────────────────────

export default function BOMSheet() {
  const [loading, setLoading] = useState(true);
  const [source, setSource] = useState<'saved' | 'generated' | null>(null);
  const [fetchError, setFetchError] = useState<string | null>(null);
  const [saveStatus, setSaveStatus] = useState<'idle' | 'saving' | 'saved' | 'error'>('idle');

  const { control, register, handleSubmit, reset } = useForm<FormValues>({
    defaultValues: { rows: [] },
  });

  const { fields, append, remove } = useFieldArray({ control, name: 'rows' });

  useEffect(() => {
    setLoading(true);
    fetch(`/api/proposal/${PROPOSAL_ID}/bom`)
      .then((r) => {
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        return r.json() as Promise<ApiResponse>;
      })
      .then((res) => {
        setSource(res.source);
        reset({ rows: res.data.map(apiRowToFormRow) });
        setLoading(false);
      })
      .catch((e: Error) => {
        setFetchError(e.message);
        setLoading(false);
      });
  }, [reset]);

  const onSubmit = async (data: FormValues) => {
    setSaveStatus('saving');
    try {
      const payload = {
        rows: data.rows.map((r) => ({
          itemName: r.itemName,
          specification: r.specification,
          quantity: parseFloat(r.quantity) || 0,
          brand: r.brand,
          warranty: r.warranty,
        })),
      };

      const res = await fetch(`/api/proposal/${PROPOSAL_ID}/bom`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
      });

      if (!res.ok) {
        const err = (await res.json()) as { error: string };
        throw new Error(err.error);
      }

      const saved = (await res.json()) as ApiResponse;
      setSource('saved');
      reset({ rows: saved.data.map(apiRowToFormRow) });
      setSaveStatus('saved');
      setTimeout(() => setSaveStatus('idle'), 2500);
    } catch {
      setSaveStatus('error');
      setTimeout(() => setSaveStatus('idle'), 3000);
    }
  };

  return (
    <div>
      {/* Page card */}
      <div className="bg-gradient-to-br from-white via-primary-50/40 to-white shadow-2xl rounded-2xl border-2 border-primary-200/50 overflow-hidden backdrop-blur-sm">
        {/* Header strip */}
        <div className="px-6 py-5 sm:px-8 sm:py-6" style={{ background: 'linear-gradient(to right, #0d1b3a, #1e2848, #eab308)' }}>
          <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
            <div className="flex items-center gap-3">
              <div className="p-2.5 rounded-xl bg-white/25 border border-white/40 shadow-lg backdrop-blur-md text-xl leading-none">
                🔩
              </div>
              <div>
                <h1 className="text-xl sm:text-2xl font-extrabold text-white drop-shadow">
                  Bill of Materials
                </h1>
                <p className="mt-0.5 text-white/90 text-sm">
                  Auto-generated from costing items. Edit brand, warranty, and specs as needed.
                </p>
              </div>
            </div>

            {source && (
              <span
                className={`text-xs px-3 py-1.5 rounded-full border font-semibold flex-shrink-0 ${
                  source === 'saved'
                    ? 'bg-emerald-50 text-emerald-700 border-emerald-200'
                    : 'bg-white/20 text-white border-white/40'
                }`}
              >
                {source === 'saved' ? 'Saved overrides' : 'Auto-generated'}
              </span>
            )}
          </div>
        </div>

        {/* Content */}
        <div className="px-4 sm:px-6 md:px-8 py-6 sm:py-8">
          {/* Loading */}
          {loading && (
            <div className="flex items-center gap-3 text-secondary-500 text-sm py-12 justify-center">
              <span className="w-4 h-4 border-2 border-primary-200 border-t-primary-600 rounded-full animate-spin" />
              Generating BOM from costing items…
            </div>
          )}

          {/* Error */}
          {fetchError && (
            <div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-amber-800 text-sm">
              Failed to load BOM: {fetchError}
            </div>
          )}

          {!loading && !fetchError && (
            <form onSubmit={handleSubmit(onSubmit)}>
              {/* Table */}
              <div className="bg-white rounded-xl shadow-sm border border-primary-100 overflow-x-auto">
                <table className="w-full border-collapse min-w-[800px]">
                  <thead>
                    <tr className="border-b border-primary-100 bg-primary-50/60">
                      <th className="px-3 py-3 text-left text-xs font-semibold text-secondary-500 uppercase tracking-wide w-16">
                        Source
                      </th>
                      <th className="px-3 py-3 text-left text-xs font-semibold text-secondary-500 uppercase tracking-wide">
                        Item / Description
                      </th>
                      <th className="px-3 py-3 text-left text-xs font-semibold text-secondary-500 uppercase tracking-wide">
                        Specification
                      </th>
                      <th className="px-3 py-3 text-right text-xs font-semibold text-secondary-500 uppercase tracking-wide w-20">
                        Qty
                      </th>
                      <th className="px-3 py-3 text-left text-xs font-semibold text-secondary-500 uppercase tracking-wide w-36">
                        Brand
                      </th>
                      <th className="px-3 py-3 text-left text-xs font-semibold text-secondary-500 uppercase tracking-wide w-28">
                        Warranty
                      </th>
                      <th className="w-8" />
                    </tr>
                  </thead>

                  <tbody>
                    {fields.length === 0 ? (
                      <tr>
                        <td colSpan={7} className="px-4 py-10 text-center text-secondary-400 text-sm">
                          No costing items found. Add items in the Costing Sheet first.
                        </td>
                      </tr>
                    ) : (
                      fields.map((field, index) => (
                        <BomRowInput
                          key={field.id}
                          index={index}
                          control={control}
                          register={register}
                          onRemove={() => remove(index)}
                        />
                      ))
                    )}
                  </tbody>

                  {fields.length > 0 && (
                    <tfoot>
                      <tr className="border-t-2 border-primary-200 bg-primary-50/60">
                        <td colSpan={3} className="px-3 py-3 text-xs text-secondary-500 uppercase tracking-wide font-medium">
                          Total items
                        </td>
                        <td className="px-3 py-3 text-right text-sm text-secondary-800 font-semibold tabular-nums">
                          {fields.length}
                        </td>
                        <td colSpan={3} />
                      </tr>
                    </tfoot>
                  )}
                </table>
              </div>

              {/* Actions */}
              <div className="mt-4 flex flex-wrap items-center justify-between gap-3">
                <button
                  type="button"
                  onClick={() => append({ ...EMPTY_ROW })}
                  className="flex items-center gap-2 text-sm text-primary-600 hover:text-primary-800 transition-colors px-3 py-2 rounded-lg hover:bg-primary-50 border border-primary-200 font-medium"
                >
                  <span className="text-lg leading-none">+</span>
                  Add row
                </button>

                <div className="flex items-center gap-3">
                  {saveStatus === 'saved' && (
                    <span className="text-xs text-emerald-600 font-medium">Saved ✓</span>
                  )}
                  {saveStatus === 'error' && (
                    <span className="text-xs text-red-500">Save failed</span>
                  )}

                  <button
                    type="submit"
                    disabled={saveStatus === 'saving'}
                    className="text-sm bg-primary-600 hover:bg-primary-700 disabled:opacity-50 text-white px-5 py-2 rounded-xl transition-all font-semibold shadow-lg hover:shadow-xl flex items-center gap-2"
                  >
                    {saveStatus === 'saving' && (
                      <span className="w-3 h-3 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                    )}
                    Save BOM
                  </button>
                </div>
              </div>
            </form>
          )}

          {/* Info panel */}
          {!loading && !fetchError && (
            <div className="mt-8 bg-gradient-to-br from-primary-50/30 to-transparent border-t border-primary-100 rounded-xl p-5">
              <h3 className="text-sm font-semibold text-secondary-600 mb-3">How BOM generation works</h3>
              <ol className="space-y-2 text-xs text-secondary-500">
                <li className="flex items-start gap-2">
                  <span className="px-2 py-0.5 rounded-md text-xs font-semibold bg-primary-600 text-white shadow-sm flex-shrink-0">1</span>
                  Costing items with the same name and category are grouped and their quantities summed.
                </li>
                <li className="flex items-start gap-2">
                  <span className="px-2 py-0.5 rounded-md text-xs font-semibold bg-primary-600 text-white shadow-sm flex-shrink-0">2</span>
                  Default brand, warranty, and specification are filled from solar-industry standards per category.
                </li>
                <li className="flex items-start gap-2">
                  <span className="px-2 py-0.5 rounded-md text-xs font-semibold bg-primary-600 text-white shadow-sm flex-shrink-0">3</span>
                  Edit any field and click <strong className="text-secondary-700">Save BOM</strong> — your overrides are persisted and won't be overwritten on the next load.
                </li>
                <li className="flex items-start gap-2">
                  <span className="px-2 py-0.5 rounded-md text-xs font-semibold bg-primary-600 text-white shadow-sm flex-shrink-0">4</span>
                  Add manual rows for items not in the costing sheet (accessories, transport, etc.).
                </li>
              </ol>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
