import React, { useEffect, useState, useCallback, useRef } from 'react';
import { useForm, useFieldArray, useWatch } from 'react-hook-form';
import { Link } from 'react-router-dom';
import {
  CATEGORIES, CATEGORY_COLORS, catAccentColor, snapCategory,
} from '../lib/costingConstants';
import type { StoredBom, RoiAutofill } from '../lib/costingConstants';
import * as XLSX from 'xlsx';
import { getActiveCustomer, upsertCustomer, getWipKeysForCurrentUser } from '../lib/customerStore';
import type { BomArtifact } from '../lib/customerStore';
import { syncProjectBom, canEditProposalArtifacts } from '../lib/apiClient';
import { AlertCard } from '../components/AlertCard';

// ─────────────────────────────────────────────
// Export helpers (BOM)
// ─────────────────────────────────────────────

function exportBomXlsx(rows: BomRow[], sheetName: string) {
  const headerRow = ['#', 'Item / Description', 'Specification', 'Qty', 'Brand', 'GST %'];
  const dataRows  = rows
    .filter((r) => r.itemName.trim())
    .map((r, i) => [
      i + 1,
      r.itemName,
      r.specification,
      parseFloat(r.quantity) || 0,
      r.brand || '',
      deriveGstRate(r.itemName),
    ]);

  const totalQty = rows.reduce((s, r) => s + (parseFloat(r.quantity) || 0), 0);
  const blankRow = ['', '', '', '', '', ''];
  const totalRow = ['', 'TOTAL LINE ITEMS', '', totalQty, '', ''];
  const countRow = ['', 'TOTAL ITEMS IN BOM', '', `${rows.filter((r) => r.itemName.trim()).length} line items`, '', ''];

  const allRows = [headerRow, ...dataRows, blankRow, totalRow, countRow];

  const ws = XLSX.utils.aoa_to_sheet(allRows);
  ws['!cols'] = [{ wch: 4 }, { wch: 36 }, { wch: 24 }, { wch: 8 }, { wch: 20 }, { wch: 8 }];

  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'Bill of Materials');
  XLSX.writeFile(wb, `${sheetName.replace(/[^a-zA-Z0-9_\-. ]/g, '_')}_BOM.xlsx`);
}

function exportBomCsv(rows: BomRow[], sheetName: string) {
  const header = '#,Item / Description,Specification,Qty,Brand,GST %';

  const escape = (v: string | number) => {
    const s = String(v);
    return s.includes(',') || s.includes('"') ? `"${s.replace(/"/g, '""')}"` : s;
  };

  const dataRows = rows
    .filter((r) => r.itemName.trim())
    .map((r, i) =>
      [i + 1, r.itemName, r.specification, parseFloat(r.quantity) || 0, r.brand || '', deriveGstRate(r.itemName)].map(escape).join(','),
    );

  const totalQty  = rows.reduce((s, r) => s + (parseFloat(r.quantity) || 0), 0);
  const summaryLines = [
    `,`,
    `,"TOTAL LINE ITEMS",,${totalQty}`,
    `,"TOTAL ITEMS IN BOM",,${rows.filter((r) => r.itemName.trim()).length} line items`,
  ];

  const csv = [header, ...dataRows, ...summaryLines].join('\n');
  const blob = new Blob(['\uFEFF' + csv], { type: 'text/csv;charset=utf-8;' });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href     = url;
  a.download = `${sheetName.replace(/[^a-zA-Z0-9_\-. ]/g, '_')}_BOM.csv`;
  a.click();
  URL.revokeObjectURL(url);
}

// ─────────────────────────────────────────────
// GST rates — post 56th GST Council (Sep 2025)
// ─────────────────────────────────────────────

/**
 * Derive applicable GST rate from item name keywords.
 * PV Modules & on-grid Inverters → 5%  (post 56th GST Council, Sep 2025)
 * All other items (structure, boards, cables, earthing, meter, installation, others) → 18%
 */
function deriveGstRate(itemName: string): number {
  const n = itemName.toLowerCase();
  if (
    n.includes('module') || n.includes('panel') || n.includes('solar cell') ||
    n.includes('perc') || n.includes('bifacial') || n.includes('mono') || n.includes('pv ') ||
    n.includes('inverter') || n.includes('string inverter') || n.includes('on-grid') ||
    n.includes('ongrid') || n.includes('grid tie') || n.includes('grid-tie')
  ) return 5;
  return 18;
}

// ─────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────

interface BomRow {
  category: string;
  itemName: string;
  specification: string;
  quantity: string;
  brand: string;
  isAutoGenerated: boolean;
}

interface FormValues {
  rows: BomRow[];
}


const EMPTY_ROW: BomRow = {
  category: 'others',
  itemName: '',
  specification: '',
  quantity: '1',
  brand: '',
  isAutoGenerated: false,
};

/** Ensure legacy rows have a category and migrate old keys to new ones */
function normalizeRow(r: Partial<BomRow>): BomRow {
  return {
    category:        snapCategory(r.category ?? 'others', r.itemName ?? ''),
    itemName:        r.itemName ?? '',
    specification:   r.specification ?? '',
    quantity:        r.quantity ?? '1',
    brand:           r.brand ?? '',
    isAutoGenerated: r.isAutoGenerated ?? false,
  };
}

interface BomOverrides {
  sheetId: string;
  rows:    BomRow[];
  savedAt: string;
}

function loadOverrides(): BomOverrides | null {
  try {
    const key = getWipKeysForCurrentUser().bomOverrides;
    const raw = localStorage.getItem(key);
    return raw ? JSON.parse(raw) : null;
  } catch { return null; }
}

function persistOverrides(sheetId: string, rows: BomRow[]) {
  const wip = getWipKeysForCurrentUser();
  const data: BomOverrides = { sheetId, rows, savedAt: new Date().toISOString() };
  localStorage.setItem(wip.bomOverrides, JSON.stringify(data));
}

function loadStoredBom(): StoredBom | null {
  try {
    const key = getWipKeysForCurrentUser().bomCosting;
    const raw = localStorage.getItem(key);
    return raw ? JSON.parse(raw) : null;
  } catch { return null; }
}

// ─────────────────────────────────────────────
// GST Summary Panel
// ─────────────────────────────────────────────

/**
 * Shows a GST rate reference table with current India solar rates.
 * Since BOM rows don't have unit costs, this is a reference/info panel
 * showing which items attract which GST rate.
 */
function GstSummaryPanel({ rows }: { rows: BomRow[] }) {
  // Classify each item
  const at5  = rows.filter((r) => deriveGstRate(r.itemName ?? '') === 5);
  const at18 = rows.filter((r) => deriveGstRate(r.itemName ?? '') === 18);

  return (
    <div className="mt-6 bg-gradient-to-br from-blue-50/60 to-white rounded-xl border border-blue-100 shadow-sm overflow-hidden">
      {/* Panel header */}
      <div className="px-5 py-3 border-b border-blue-100 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <span className="text-base">🧾</span>
          <h3 className="text-sm font-bold text-primary-800">GST Applicability — Solar Project</h3>
        </div>
        <span className="text-[10px] text-blue-600 bg-blue-50 border border-blue-200 px-2 py-0.5 rounded-full font-semibold">
          Post 56th GST Council · Sep 2025
        </span>
      </div>

      <div className="p-5 grid grid-cols-1 sm:grid-cols-2 gap-5">
        {/* 5% bucket */}
        <div className="rounded-xl border border-emerald-200 bg-emerald-50/60 p-4">
          <div className="flex items-center gap-2 mb-3">
            <span className="text-lg font-extrabold text-emerald-700">5%</span>
            <span className="text-xs text-emerald-600 font-medium">GST</span>
            <span className="text-[10px] text-emerald-500 ml-auto">HSN 8541 / 8504</span>
          </div>
          <p className="text-xs text-emerald-700 font-semibold mb-2">Solar Modules & On-Grid Inverters</p>
          {at5.length > 0 ? (
            <ul className="space-y-1">
              {at5.map((r, i) => (
                <li key={i} className="text-xs text-emerald-600 flex items-center gap-1.5">
                  <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 flex-shrink-0" />
                  {r.itemName || <span className="italic text-emerald-400">Unnamed item</span>}
                </li>
              ))}
            </ul>
          ) : (
            <p className="text-xs text-emerald-400 italic">No items in this category</p>
          )}
        </div>

        {/* 18% bucket */}
        <div className="rounded-xl border border-blue-200 bg-blue-50/60 p-4">
          <div className="flex items-center gap-2 mb-3">
            <span className="text-lg font-extrabold text-blue-700">18%</span>
            <span className="text-xs text-blue-600 font-medium">GST</span>
            <span className="text-[10px] text-blue-500 ml-auto">HSN 7308 / 8544 / Service</span>
          </div>
          <p className="text-xs text-blue-700 font-semibold mb-2">Structure, Cable, Labour & Misc</p>
          {at18.length > 0 ? (
            <ul className="space-y-1">
              {at18.map((r, i) => (
                <li key={i} className="text-xs text-blue-600 flex items-center gap-1.5">
                  <span className="w-1.5 h-1.5 rounded-full bg-blue-400 flex-shrink-0" />
                  {r.itemName || <span className="italic text-blue-400">Unnamed item</span>}
                </li>
              ))}
            </ul>
          ) : (
            <p className="text-xs text-blue-400 italic">No items in this category</p>
          )}
        </div>
      </div>

      {/* Rate reference footer */}
      <div className="px-5 py-3 border-t border-blue-100 bg-white/60">
        <p className="text-[10px] text-secondary-400 leading-relaxed">
          <strong className="text-secondary-500">Note:</strong> GST classification is auto-detected from item names.
          Hybrid inverters attract 18% GST. For composite EPC contracts, an effective blended rate of ~8.7% may apply
          (70% goods @ 5% + 30% services @ 18%). Consult your CA for final tax computation.
        </p>
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────
// BOM row component
// ─────────────────────────────────────────────

function BomRowInput({
  index,
  control,
  register,
  onRemove,
  category,
  canEdit,
}: {
  index:    number;
  control:  ReturnType<typeof useForm<FormValues>>['control'];
  register: ReturnType<typeof useForm<FormValues>>['register'];
  onRemove: () => void;
  category?: string;
  canEdit:  boolean;
}) {
  const isAuto   = useWatch({ control, name: `rows.${index}.isAutoGenerated` });
  const itemName = useWatch({ control, name: `rows.${index}.itemName` }) as string;
  const gstRate  = deriveGstRate(itemName ?? '');
  const accent   = catAccentColor(category ?? 'others');

  return (
    <tr className="group border-b border-primary-100/60 hover:bg-primary-50/40 transition-colors">
      {/* Category pill */}
      <td className="px-3 py-2 w-36">
        <span
          className={`text-[10px] px-2 py-0.5 rounded-full border font-semibold ${CATEGORY_COLORS[category as keyof typeof CATEGORY_COLORS] ?? ''}`}
          style={{ borderColor: `${accent}40` }}
        >
          {CATEGORIES.find((c) => c.value === category)?.label ?? category ?? '—'}
        </span>
      </td>
      {/* Auto badge */}
      <td className="px-3 py-2 w-16 text-center">
        {isAuto ? (
          <span className="text-[10px] px-1.5 py-0.5 rounded border bg-primary-50 text-primary-600 border-primary-200 whitespace-nowrap font-medium">auto</span>
        ) : (
          <span className="text-[10px] px-1.5 py-0.5 rounded border bg-yellow-50 text-yellow-700 border-yellow-200 whitespace-nowrap font-medium">manual</span>
        )}
      </td>

      {/* Item name */}
      <td className="px-3 py-2">
        <input
          {...register(`rows.${index}.itemName`)}
          placeholder="Item name"
          readOnly={!canEdit}
          className="w-full bg-transparent text-sm text-secondary-800 placeholder-secondary-400 focus:outline-none disabled:cursor-not-allowed disabled:opacity-70"
        />
      </td>

      {/* Specification */}
      <td className="px-3 py-2">
        <input
          {...register(`rows.${index}.specification`)}
          placeholder="e.g. Mono PERC, 540W"
          readOnly={!canEdit}
          className="w-full bg-transparent text-sm text-secondary-600 placeholder-secondary-400 focus:outline-none disabled:cursor-not-allowed disabled:opacity-70"
        />
      </td>

      {/* Qty */}
      <td className="px-3 py-2 w-20">
        <input
          {...register(`rows.${index}.quantity`)}
          type="number" min="0" step="any" placeholder="0"
          readOnly={!canEdit}
          className="w-full bg-transparent text-sm text-right text-secondary-800 placeholder-secondary-400 focus:outline-none tabular-nums disabled:cursor-not-allowed disabled:opacity-70"
        />
      </td>

      {/* Brand */}
      <td className="px-3 py-2 w-36">
        <input
          {...register(`rows.${index}.brand`)}
          placeholder="Brand"
          readOnly={!canEdit}
          className="w-full bg-transparent text-sm text-secondary-600 placeholder-secondary-400 focus:outline-none disabled:cursor-not-allowed disabled:opacity-70"
        />
      </td>

      {/* GST % — derived from item name, read-only */}
      <td className="px-3 py-2 w-20 text-center">
        <span className={`text-xs font-bold px-2 py-0.5 rounded-full border ${
          gstRate === 5
            ? 'bg-emerald-50 text-emerald-700 border-emerald-200'
            : 'bg-blue-50 text-blue-700 border-blue-200'
        }`}>
          {gstRate}%
        </span>
      </td>

      {/* Remove — hidden for read-only */}
      <td className="px-2 py-2 w-8 text-center">
        {canEdit && (
        <button
          type="button" onClick={onRemove} title="Remove row"
          className="opacity-0 group-hover:opacity-100 transition-opacity text-secondary-400 hover:text-red-500 text-lg leading-none"
        >×</button>
        )}
      </td>
    </tr>
  );
}

// ─────────────────────────────────────────────
// Grouped BOM table (single <table>, category group header rows)
// ─────────────────────────────────────────────

function BomTable({
  fields, control, register, remove, append, liveRows, initialRows, allCollapsed, canEdit,
}: {
  fields:       { id: string }[];
  control:      ReturnType<typeof useForm<FormValues>>['control'];
  register:     ReturnType<typeof useForm<FormValues>>['register'];
  remove:       (index: number) => void;
  append:       (row: BomRow) => void;
  liveRows:     BomRow[];
  initialRows:  BomRow[];
  allCollapsed: boolean;
  canEdit:      boolean;
}) {
  const [collapsed, setCollapsed] = useState<Set<string>>(new Set());
  const toggle = (cat: string) =>
    setCollapsed((prev) => { const n = new Set(prev); n.has(cat) ? n.delete(cat) : n.add(cat); return n; });

  // Sync to parent's expand/collapse-all signal
  const prevAllCollapsed = React.useRef(allCollapsed);
  useEffect(() => {
    if (prevAllCollapsed.current === allCollapsed) return;
    prevAllCollapsed.current = allCollapsed;
    if (allCollapsed) {
      setCollapsed(new Set(CATEGORIES.map((c) => c.value)));
    } else {
      setCollapsed(new Set());
    }
  }, [allCollapsed]);

  // Use liveRows for category when available, fall back to initialRows (always correct on first render)
  const getCat = (i: number): string =>
    liveRows[i]?.category || initialRows[i]?.category || 'others';

  const grouped = CATEGORIES.map((cat) => ({
    cat,
    indices: fields.map((_, i) => i).filter((i) => getCat(i) === cat.value),
  })).filter((g) => g.indices.length > 0);

  if (fields.length === 0 || (fields.length === 1 && !liveRows[0]?.itemName)) {
    return (
      <div className="bg-white rounded-xl shadow-sm border border-primary-100 px-4 py-10 text-center text-secondary-400 text-sm">
        No BOM items yet. Save a Costing Sheet first to auto-generate the BOM.
      </div>
    );
  }

  return (
    <div className="bg-white rounded-xl shadow-sm border border-primary-100 overflow-x-auto">
      <table className="w-full border-collapse min-w-[920px]">
        <thead>
          <tr className="border-b-2 border-primary-200 bg-primary-50/80">
            <th className="px-3 py-3 text-left text-xs font-semibold text-secondary-500 uppercase tracking-wide w-36">Category</th>
            <th className="px-3 py-3 text-left text-xs font-semibold text-secondary-500 uppercase tracking-wide w-16">Source</th>
            <th className="px-3 py-3 text-left text-xs font-semibold text-secondary-500 uppercase tracking-wide">Item / Description</th>
            <th className="px-3 py-3 text-left text-xs font-semibold text-secondary-500 uppercase tracking-wide">Specification</th>
            <th className="px-3 py-3 text-right text-xs font-semibold text-secondary-500 uppercase tracking-wide w-20">Qty</th>
            <th className="px-3 py-3 text-left text-xs font-semibold text-secondary-500 uppercase tracking-wide w-36">Brand</th>
            <th className="px-3 py-3 text-center text-xs font-semibold text-blue-600 uppercase tracking-wide w-20">GST %</th>
            <th className="w-8" />
          </tr>
        </thead>
        <tbody>
          {grouped.map(({ cat, indices }) => {
            const isOpen   = !collapsed.has(cat.value);
            const accent   = catAccentColor(cat.value);
            const catRows  = indices.map((i) => liveRows[i]).filter(Boolean);
            const totalQty = catRows.reduce((s, r) => s + (parseFloat(r.quantity) || 0), 0);

            return (
              <React.Fragment key={cat.value}>
                {/* ── Category group header row ── */}
                <tr
                  className="cursor-pointer select-none hover:brightness-95 transition-all"
                  style={{ background: `${accent}18`, borderTop: `2px solid ${accent}40` }}
                  onClick={() => toggle(cat.value)}
                >
                  <td colSpan={9} className="px-3 py-2">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-2.5">
                        <span
                          className="text-xs font-bold transition-transform duration-200 inline-block"
                          style={{ color: accent, transform: isOpen ? 'rotate(90deg)' : 'rotate(0deg)' }}
                        >▶</span>
                        <span className={`text-xs px-2.5 py-0.5 rounded-full border font-bold ${CATEGORY_COLORS[cat.value as keyof typeof CATEGORY_COLORS] ?? ''}`}>
                          {cat.label}
                        </span>
                        <span className="text-xs text-secondary-500">
                          {indices.length} item{indices.length !== 1 ? 's' : ''}
                        </span>
                      </div>
                      <div className="flex items-center gap-3">
                        {totalQty > 0 && (
                          <span className="text-xs font-bold tabular-nums" style={{ color: accent }}>
                            Qty: {totalQty.toLocaleString('en-IN')}
                          </span>
                        )}
                        {canEdit && (
                        <button
                          type="button"
                          onClick={(e) => {
                            e.stopPropagation();
                            append({ ...EMPTY_ROW, category: cat.value });
                            setCollapsed((prev) => { const n = new Set(prev); n.delete(cat.value); return n; });
                          }}
                          className="text-xs font-semibold px-2.5 py-0.5 rounded-lg border transition-colors hover:opacity-80"
                          style={{ color: accent, borderColor: `${accent}60`, background: 'white' }}
                        >
                          + Add row
                        </button>
                        )}
                      </div>
                    </div>
                  </td>
                </tr>

                {/* ── Data rows ── */}
                {isOpen && indices.map((globalIdx) => (
                  <BomRowInput
                    key={fields[globalIdx]?.id ?? globalIdx}
                    index={globalIdx}
                    control={control}
                    register={register}
                    onRemove={() => remove(globalIdx)}
                    category={cat.value}
                    canEdit={canEdit}
                  />
                ))}

                {/* ── Category qty subtotal ── */}
                {isOpen && totalQty > 0 && (
                  <tr style={{ background: `${accent}08`, borderBottom: `1px solid ${accent}30` }}>
                    <td colSpan={4} className="px-3 py-1.5 text-xs text-secondary-400 italic pl-10">
                      {cat.label} subtotal
                    </td>
                    <td className="px-3 py-1.5 text-right text-sm font-bold tabular-nums" style={{ color: accent }}>
                      {totalQty.toLocaleString('en-IN')}
                    </td>
                    <td colSpan={4} />
                  </tr>
                )}
              </React.Fragment>
            );
          })}
        </tbody>
      </table>
    </div>
  );
}

// ─────────────────────────────────────────────
// Main page
// ─────────────────────────────────────────────

export default function BOMSheet() {
  // Resolve initial rows synchronously to avoid useEffect lag
  const _initRows = (() => {
    const ac = getActiveCustomer();
    if (ac?.bom?.rows && ac.bom.rows.length > 0)
      return (ac.bom.rows as Partial<BomRow>[]).map(normalizeRow);
    const stored = loadStoredBom();
    if (stored) {
      const overrides = loadOverrides();
      if (overrides && overrides.sheetId === stored.sheetId)
        return overrides.rows.map(normalizeRow);
      return (stored.rows as Partial<BomRow>[]).map(normalizeRow);
    }
    return [];
  })();

  // Keep a ref so BomTable always has correct categories on first render
  const initialRowsRef = useRef<BomRow[]>(_initRows);

  const [loading, setLoading]       = useState(_initRows.length === 0);
  const [source, setSource]         = useState<'costing-sheet' | 'overrides' | 'api' | null>(
    _initRows.length > 0 ? 'overrides' : null
  );
  const [storedBom, setStoredBom]   = useState<StoredBom | null>(loadStoredBom);
  const [fetchError, setFetchError] = useState<string | null>(null);
  const [saveStatus, setSaveStatus] = useState<'idle' | 'saving' | 'saved' | 'error'>('idle');
  const [allCollapsed, setAllCollapsed] = useState(false);

  const canEdit = canEditProposalArtifacts();

  const { control, register, handleSubmit, reset } = useForm<FormValues>({
    defaultValues: { rows: _initRows },
  });

  const { fields, append, remove } = useFieldArray({ control, name: 'rows' });
  const watchedRows = useWatch({ control, name: 'rows' }) as BomRow[] | undefined;
  const liveRows = watchedRows ?? [];

  const loadBom = useCallback((force = false) => {
    // If we already loaded synchronously on init, skip unless forced
    if (!force && _initRows.length > 0) {
      setLoading(false);
      return;
    }

    setLoading(true);
    setFetchError(null);

    // 1. Prefer active customer's saved BOM artifact
    const ac = getActiveCustomer();
    if (ac?.bom?.rows && ac.bom.rows.length > 0) {
      const rows = (ac.bom.rows as Partial<BomRow>[]).map(normalizeRow);
      initialRowsRef.current = rows;
      reset({ rows });
      setSource('overrides');
      setLoading(false);
      return;
    }

    // 2. Fall back to localStorage costing-sheet-generated BOM
    const stored = loadStoredBom();
    setStoredBom(stored);

    if (stored) {
      const overrides = loadOverrides();
      if (overrides && overrides.sheetId === stored.sheetId) {
        const rows = overrides.rows.map(normalizeRow);
        initialRowsRef.current = rows;
        reset({ rows });
        setSource('overrides');
      } else {
        const rows = (stored.rows as Partial<BomRow>[]).map(normalizeRow);
        initialRowsRef.current = rows;
        reset({ rows });
        setSource('costing-sheet');
      }
      setLoading(false);
      return;
    }

    // No localStorage data and no backend in production — start with empty BOM
    setSource('costing-sheet');
    setLoading(false);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [reset]);

  useEffect(() => { loadBom(); }, [loadBom]);

  const onSubmit = useCallback((data: FormValues) => {
    setSaveStatus('saving');
    try {
      const now     = new Date().toISOString();
      const sheetId = storedBom?.sheetId ?? 'manual';
      persistOverrides(sheetId, data.rows);
      setSource('overrides');

      // Forward ROI autofill from the costing sheet (BOM doesn't have costs,
      // so we preserve whatever the costing sheet wrote — just update the source label)
      try {
        const wip = getWipKeysForCurrentUser();
        const existing = localStorage.getItem(wip.roiAutofill);
        if (existing) {
          const prev: RoiAutofill = JSON.parse(existing);
          const updated: RoiAutofill = {
            ...prev,
            source:     'bom',
            sourceName: storedBom?.sheetName ?? prev.sourceName,
            savedAt:    now,
          };
          localStorage.setItem(wip.roiAutofill, JSON.stringify(updated));
        }
      } catch { /* ignore */ }

      // Persist BOM artifact to active customer record
      const activeCustomer = getActiveCustomer();
      if (activeCustomer) {
        const artifact: BomArtifact = { savedAt: now, rows: data.rows };
        upsertCustomer({ ...activeCustomer, bom: artifact, updatedAt: now });

        // Best-effort sync to CRM backend for CRM-linked projects.
        if (activeCustomer.master.crmProjectId) {
          void syncProjectBom(activeCustomer.master.crmProjectId, artifact);
        }
      }

      setSaveStatus('saved');
      setTimeout(() => setSaveStatus('idle'), 2500);
    } catch {
      setSaveStatus('error');
      setTimeout(() => setSaveStatus('idle'), 3000);
    }
  }, [storedBom]);

  const handleRegenerateFromCosting = useCallback(() => {
    const stored = loadStoredBom();
    if (!stored) return;
    // Clear overrides and reload the raw generated rows
    localStorage.removeItem(getWipKeysForCurrentUser().bomOverrides);
    const rows = (stored.rows as Partial<BomRow>[]).map(normalizeRow);
    initialRowsRef.current = rows;
    reset({ rows });
    setSource('costing-sheet');
  }, [reset]);

  return (
    <div>
      {/* Page card */}
      <div className="bg-gradient-to-br from-white via-primary-50/40 to-white shadow-2xl rounded-2xl border-2 border-primary-200/50 overflow-hidden backdrop-blur-sm">
        {/* Header strip */}
        <div className="px-6 py-5 sm:px-8 sm:py-6" style={{ background: 'linear-gradient(to right, #0d1b3a, #1e2848, #eab308)' }}>
            <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
            <div className="flex items-center gap-3">
              <div className="p-2.5 rounded-xl bg-white/25 border border-white/40 shadow-lg backdrop-blur-md text-xl leading-none">
                🔩
              </div>
              <div>
                <h1 className="text-xl sm:text-2xl font-extrabold text-white drop-shadow">
                  Bill of Materials
                </h1>
                <p className="mt-0.5 text-white/90 text-sm">
                  Auto-generated from costing items. Edit brand and specs as needed.
                </p>
              </div>
            </div>

            <div className="flex flex-col gap-2 w-full sm:w-auto flex-shrink-0">
              {/* Status badge row */}
              {source && (
                <div className="flex justify-start sm:justify-end">
                  <span
                    className={`text-xs px-3 py-1.5 rounded-full border font-semibold ${
                      source === 'overrides'
                        ? 'bg-emerald-50 text-emerald-700 border-emerald-200'
                        : source === 'costing-sheet'
                        ? 'bg-yellow-50 text-yellow-700 border-yellow-200'
                        : 'bg-white/20 text-white border-white/40'
                    }`}
                  >
                    {source === 'overrides'
                      ? '✓ Saved overrides'
                      : source === 'costing-sheet'
                      ? '⚡ From Costing Sheet'
                      : 'Auto-generated'}
                  </span>
                </div>
              )}
              {/* Export & Save buttons — hidden for read-only (Ops/Finance/Management) */}
              {canEdit && fields.length > 0 && (
                <div className="flex items-center gap-2 flex-wrap justify-start sm:justify-end">
                  <button
                    type="button"
                    onClick={() => exportBomXlsx(liveRows, storedBom?.sheetName ?? 'BOM')}
                    className="flex items-center gap-1.5 text-xs text-white font-semibold bg-white/20 hover:bg-white/30 border border-white/40 px-3 py-2 rounded-lg transition-colors min-h-[36px]"
                  >
                    📤 XLSX
                  </button>
                  <button
                    type="button"
                    onClick={() => exportBomCsv(liveRows, storedBom?.sheetName ?? 'BOM')}
                    className="flex items-center gap-1.5 text-xs text-white font-semibold bg-white/20 hover:bg-white/30 border border-white/40 px-3 py-2 rounded-lg transition-colors min-h-[36px]"
                  >
                    📤 CSV
                  </button>
                  <button
                    type="button"
                    onClick={() => { void handleSubmit(onSubmit)(); }}
                    disabled={saveStatus === 'saving'}
                    className="flex items-center gap-1.5 bg-white/20 hover:bg-white/30 border-2 border-white/40 text-white text-xs font-semibold px-4 py-2 rounded-xl transition-all min-h-[36px] disabled:opacity-60"
                  >
                    💾 Save BOM
                  </button>
                </div>
              )}
            </div>
          </div>
        </div>

        {/* Content */}
        <div className="px-4 sm:px-6 md:px-8 py-6 sm:py-8">
          {/* Active customer banner */}
          {(() => {
            const ac = getActiveCustomer();
            return ac ? (
              <div className="mb-5 rounded-xl border border-sky-200 bg-sky-50 px-4 py-2.5 flex items-center justify-between gap-3">
                <p className="text-xs text-sky-700">
                  <span className="font-semibold">Active customer:</span> {ac.master.name}
                  {ac.bom && <span className="ml-2 text-emerald-600 font-medium">· BOM saved ✓</span>}
                </p>
                <Link to="/" className="text-xs text-sky-600 hover:text-sky-800 font-medium whitespace-nowrap transition-colors">
                  View Dashboard →
                </Link>
              </div>
            ) : (
              <div className="mb-5 rounded-xl border border-amber-200 bg-amber-50 px-4 py-2.5 flex items-center justify-between gap-3">
                <p className="text-xs text-amber-700">No active customer. BOM will save to scratchpad only.</p>
                <Link to="/customers" className="text-xs text-amber-700 hover:text-amber-900 font-semibold border border-amber-300 hover:bg-amber-100 px-3 py-1 rounded-lg transition-colors whitespace-nowrap">
                  Select Customer →
                </Link>
              </div>
            );
          })()}

          {/* Costing Sheet source banner */}
          {!loading && storedBom && (
            <div className="mb-5 rounded-xl border border-yellow-200 bg-yellow-50 px-4 py-3 flex flex-col sm:flex-row sm:items-center gap-3">
              <div className="flex items-start gap-2 flex-1">
                <span className="text-lg flex-shrink-0">⚡</span>
                <div>
                  <p className="text-sm font-semibold text-yellow-800">
                    BOM auto-generated from Costing Sheet
                  </p>
                  <p className="text-xs text-yellow-700 mt-0.5">
                    Source: <strong>{storedBom.sheetName}</strong> ·{' '}
                    {new Date(storedBom.generatedAt).toLocaleDateString('en-IN', {
                      day: '2-digit', month: 'short', year: 'numeric',
                    })}{' '}
                    {new Date(storedBom.generatedAt).toLocaleTimeString('en-IN', {
                      hour: '2-digit', minute: '2-digit',
                    })}
                    {source === 'overrides' && (
                      <span className="ml-2 text-emerald-700 font-medium">· Your edits are saved</span>
                    )}
                  </p>
                </div>
              </div>
              <div className="flex items-center gap-2 flex-shrink-0">
                {canEdit && source === 'overrides' && (
                  <button
                    type="button"
                    onClick={handleRegenerateFromCosting}
                    className="text-xs text-yellow-700 hover:text-yellow-900 border border-yellow-300 hover:bg-yellow-100 px-3 py-1.5 rounded-lg transition-colors font-medium"
                  >
                    ↺ Reset to generated
                  </button>
                )}
                <span className="text-xs text-yellow-600 bg-yellow-100 border border-yellow-200 px-2.5 py-1 rounded-lg font-medium">
                  {storedBom.rows.length} items
                </span>
              </div>
            </div>
          )}

          {/* Loading */}
          {loading && (
            <div className="flex items-center gap-3 text-secondary-500 text-sm py-12 justify-center">
              <span className="w-4 h-4 border-2 border-primary-200 border-t-primary-600 rounded-full animate-spin" />
              Loading BOM…
            </div>
          )}

          {/* Error */}
          {fetchError && (
            <AlertCard
              variant="warning"
              title="Unable to load BOM"
              message={fetchError}
              className="mb-4"
            />
          )}

          {!loading && !fetchError && (
            <form onSubmit={handleSubmit(onSubmit)}>
              {/* ── Expand / Collapse All bar ── */}
              <div className="flex items-center justify-between mb-3 px-1">
                <span className="text-xs text-secondary-400 font-medium">
                  {fields.length} item{fields.length !== 1 ? 's' : ''} in BOM
                </span>
                <button
                  type="button"
                  onClick={() => setAllCollapsed((v) => !v)}
                  className="flex items-center gap-1.5 text-xs font-semibold px-3 py-1.5 rounded-full border transition-all"
                  style={allCollapsed
                    ? { background: '#0d1b3a', color: 'white', borderColor: '#0d1b3a' }
                    : { background: 'white', color: '#0d1b3a', borderColor: '#0d1b3a40' }
                  }
                >
                  <span>{allCollapsed ? '▶▶' : '▼▼'}</span>
                  {allCollapsed ? 'Expand All' : 'Collapse All'}
                </button>
              </div>

              {/* Grouped BOM table */}
              <BomTable
                fields={fields}
                control={control}
                register={register}
                remove={remove}
                append={append}
                liveRows={liveRows}
                initialRows={initialRowsRef.current}
                allCollapsed={allCollapsed}
                canEdit={canEdit}
              />

              {/* Grand total */}
              {fields.length > 0 && liveRows.some((r) => r.itemName) && (
                <div
                  className="mt-3 rounded-xl overflow-hidden shadow-sm"
                  style={{ background: 'linear-gradient(to right, #0d1b3a, #1e2848, #eab308)' }}
                >
                  <div className="flex items-center justify-between px-4 py-3">
                    <div>
                      <p className="text-sm font-bold text-white uppercase tracking-wide drop-shadow">Total Items in BOM</p>
                      <p className="text-xs text-white/70 mt-0.5">{fields.length} line item{fields.length !== 1 ? 's' : ''}</p>
                    </div>
                    <div className="text-right">
                      <p className="text-xs text-white/70 uppercase tracking-wide">Total Qty</p>
                      <p className="text-lg font-extrabold text-white tabular-nums drop-shadow">
                        {liveRows.reduce((s, r) => s + (parseFloat(r.quantity) || 0), 0).toLocaleString('en-IN')}
                      </p>
                    </div>
                  </div>
                </div>
              )}

              {/* Actions — hidden for read-only; only Expand/Collapse + View Dashboard remain */}
              {canEdit && (
              <div className="mt-4 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
                <div className="flex items-center gap-2 flex-wrap">
                  <button
                    type="button"
                    onClick={() => append({ ...EMPTY_ROW, category: 'others' })}
                    className="flex items-center gap-2 text-sm text-primary-600 hover:text-primary-800 transition-colors px-4 py-2.5 rounded-xl hover:bg-primary-50 border border-primary-200 font-medium min-h-[44px] sm:min-h-0"
                  >
                    <span className="text-lg leading-none">+</span>
                    Add Row (Others)
                  </button>

                </div>

                <div className="flex items-center gap-2 sm:gap-3">
                  {saveStatus === 'saved' && (
                    <span className="text-xs text-emerald-600 font-medium">Saved ✓</span>
                  )}
                  {saveStatus === 'error' && (
                    <span className="text-xs text-red-500">Save failed</span>
                  )}

                  <button
                    type="button"
                    onClick={() => {
                      if (confirm('Clear all BOM rows? This cannot be undone.')) {
                        remove(fields.map((_, i) => i));
                        append({ ...EMPTY_ROW });
                        localStorage.removeItem(getWipKeysForCurrentUser().bomOverrides);
                        setSource('costing-sheet');
                      }
                    }}
                    className="flex-1 sm:flex-none text-sm text-secondary-500 hover:text-secondary-700 transition-colors px-4 py-2.5 rounded-xl hover:bg-secondary-100 border border-secondary-200 min-h-[44px]"
                  >
                    Clear
                  </button>

                  <button
                    type="submit"
                    disabled={saveStatus === 'saving'}
                    className="flex-1 sm:flex-none text-sm disabled:opacity-50 text-white px-6 py-2.5 rounded-xl transition-all font-semibold shadow-lg hover:shadow-xl flex items-center justify-center gap-2 min-h-[44px]"
                    style={{ background: '#0d1b3a' }}
                    onMouseEnter={e => (e.currentTarget.style.background = '#0a1530')}
                    onMouseLeave={e => (e.currentTarget.style.background = '#0d1b3a')}
                  >
                    {saveStatus === 'saving' && (
                      <span className="w-3 h-3 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                    )}
                    Save BOM
                  </button>
                </div>
              </div>
              )}
            </form>
          )}

          {/* GST Summary panel */}
          {!loading && !fetchError && fields.length > 0 && (
            <GstSummaryPanel rows={liveRows} />
          )}

          {/* Info panel */}
          {!loading && !fetchError && (
            <div className="mt-8 bg-gradient-to-br from-primary-50/30 to-transparent border-t border-primary-100 rounded-xl p-5">
              <h3 className="text-sm font-semibold text-secondary-600 mb-3">How BOM generation works</h3>
              <ol className="space-y-2 text-xs text-secondary-500">
                <li className="flex items-start gap-2">
                  <span className="px-2 py-0.5 rounded-md text-xs font-semibold bg-primary-600 text-white shadow-sm flex-shrink-0">1</span>
                  Costing items with the same name and category are grouped and their quantities summed.
                </li>
                <li className="flex items-start gap-2">
                  <span className="px-2 py-0.5 rounded-md text-xs font-semibold bg-primary-600 text-white shadow-sm flex-shrink-0">2</span>
                  Default brand and specification are filled from solar-industry standards per category.
                </li>
                <li className="flex items-start gap-2">
                  <span className="px-2 py-0.5 rounded-md text-xs font-semibold bg-primary-600 text-white shadow-sm flex-shrink-0">3</span>
                  Edit any field and click <strong className="text-secondary-700">Save BOM</strong> — your overrides are persisted and won't be overwritten on the next load.
                </li>
                <li className="flex items-start gap-2">
                  <span className="px-2 py-0.5 rounded-md text-xs font-semibold bg-primary-600 text-white shadow-sm flex-shrink-0">4</span>
                  Add manual rows for items not in the costing sheet (accessories, transport, etc.).
                </li>
              </ol>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
